<!-- 
  Fullsublimation Add Product Modal for Show Page
  Same as create page's modal but with quick-mode:
  - Order Details fields auto-filled from sale context, disabled
  - "Add to Order" instead of "Add to Cart"
-->
<style>
    .product-modal .modal-dialog { max-width: 900px; }
    .product-modal .tab-content { min-height: 350px; }
    .product-modal .size-input-group { gap: 0.5rem; }
    .product-modal .size-input-group label { font-size: 0.8rem; margin-bottom: 0.2rem; }
    .product-modal .size-input-group input[type="number"] { text-align: center; }
    .product-modal .roster-row td { vertical-align: middle; padding: 2px 4px; }
    .product-modal .roster-row select { font-size: 0.85rem; }
    #subExcelDropZone { border: 2px dashed #ccc; border-radius: 8px; padding: 20px; text-align: center; cursor: pointer; background: #fafafa; transition: all 0.3s; }
    #subExcelDropZone:hover { border-color: #6c63ff; background: #f0eeff; }
    #subExcelDropZone.has-file { border-color: #28a745; background: #f0fff0; }
    .sub-size-qty { text-align: center; }
    /* Gray out redundant fields */
    .sub-quick-disabled { background: #e9ecef !important; opacity: 0.85; cursor: default !important; }
    .sub-quick-disabled:focus { box-shadow: none !important; }
</style>

<div class="modal fade product-modal" id="subAddProductModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold" id="subModalTitle">
                    <i class="fas fa-box" id="subModalTitleIcon"></i> <span id="subModalTitleText">Add Fullsublimation Product</span>
                    @if(isset($sale))<span class="badge bg-info ms-2" style="font-size:0.7rem;">To Order #{{ $sale->sales_number }}</span>@endif
                    <span id="subSaleBadge" class="badge bg-info ms-2" style="font-size:0.7rem;display:none;"></span>
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs mb-3" id="subSublimationTab" role="tablist">
                    <li class="nav-item"><button class="nav-link active" id="sub-order-details-tab" data-bs-toggle="tab" data-bs-target="#sub-order-details" type="button" role="tab">Order Details</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-specs-tab" data-bs-toggle="tab" data-bs-target="#sub-specs" type="button" role="tab">Specifications</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-sizes-tab" data-bs-toggle="tab" data-bs-target="#sub-sizes" type="button" role="tab">Sizes</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-pricing-tab" data-bs-toggle="tab" data-bs-target="#sub-pricing-body" type="button" role="tab">Pricing</button></li>
                </ul>

                <div class="tab-content" id="subSublimationTabContent">
                    <!-- TAB 1: ORDER DETAILS -->
                    <div class="tab-pane fade show active" id="sub-order-details" role="tabpanel">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <label class="form-label">Project Name *</label>
                                        <input type="text" class="form-control sub-quick-disabled" id="sub_projectName" placeholder="e.g. DANNA" required oninput="sub_autoGenerateDescription()">
                                        <div class="form-text small text-success">Auto-filled from existing order</div>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Description *</label>
                                        <input type="text" class="form-control" id="sub_description" placeholder="Auto-generated from selections" readonly style="background:#f0f0f0;cursor:default;">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Fabric *</label>
                                        <select class="form-control" id="sub_fabricSelect" onchange="sub_calculateTotal(); sub_autoGenerateDescription()">
                                            <option value="">-- Select Fabric --</option>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Designer *</label>
                                        <input type="text" class="form-control" id="sub_designer" placeholder="e.g. ALLAN - CONSOL" required>
                                    </div>
                                    <div class="col-md-4">
                                        <label class="form-label">Date Needed *</label>
                                        <input type="date" class="form-control" id="sub_dateNeeded" required>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <label class="form-label">Notes / Special Instructions</label>
                                    <textarea class="form-control" id="sub_notes" rows="2" placeholder="Additional notes..."></textarea>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="card border-primary">
                                    <div class="card-header bg-primary text-white small py-2">
                                        <i class="fas fa-image me-1"></i> Mock-up Design
                                    </div>
                                    <div class="card-body py-2 text-center">
                                        <div id="subMockupPreviewArea" class="mb-2" style="min-height:140px;display:flex;align-items:center;justify-content:center;border:2px dashed #ddd;border-radius:8px;cursor:pointer;background:#fafafa;overflow:hidden;" onclick="document.getElementById('subMockupUpload').click()">
                                            <div id="subMockupPlaceholder">
                                                <i class="fas fa-cloud-upload-alt fa-3x text-muted"></i>
                                                <p class="text-muted small mb-0 mt-1">Click to upload mock-up image</p>
                                            </div>
                                            <img id="subMockupPreview" src="" style="max-height:180px;display:none;max-width:100%;object-fit:contain;">
                                        </div>
                                        <input type="file" id="subMockupUpload" accept="image/*" style="display:none" onchange="sub_previewMockup(event)">
                                        <div id="subMockupFileInfo" class="small" style="display:none;">
                                            <span id="subMockupFileName" class="text-muted"></span>
                                            <button type="button" class="btn btn-sm btn-outline-danger ms-2 py-0 px-1" onclick="sub_removeMockup()"><i class="fas fa-times"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- TAB 2: SPECIFICATIONS -->
                    <div class="tab-pane fade" id="sub-specs" role="tabpanel">
                        <div class="alert alert-info py-2 small mb-3">
                            <i class="fas fa-info-circle me-1"></i> <strong>How to fill this out:</strong>
                            <ul class="mb-0 mt-1 ps-3">
                                <li>Pumili ng <strong>Garment Type</strong> — lalabas ang specification fields (collar type, sleeves, cuffs, etc.)</li>
                                <li>Check ang <strong>Additional Parts</strong> kung may extra parts ang order (printing front/back, patches, etc.)</li>
                                <li>Pumili ng <strong>Fabric</strong> at <strong>Designer</strong> sa <strong>Order Details tab</strong> bago pumunta dito</li>
                                <li>Kung may gusto si client na idagdag o baguhin sa specs, ilagay sa <strong>Notes</strong> sa Order Details tab</li>
                                <li class="text-warning fw-semibold">⚠ Lahat ng field na may * ay required</li>
                            </ul>
                        </div>
                        <div class="row g-3 mb-3">
                            <div class="col-md-6">
                                <label class="form-label">Garment Type *</label>
                                <select class="form-control" id="sub_garmentSelect" onchange="sub_renderSpecs(); sub_calculateTotal(); sub_autoGenerateDescription()">
                                    <option value="">-- Select Garment --</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Additional Parts</label>
                                <div id="sub_partsContainer" class="border rounded p-2 bg-light" style="max-height:80px;overflow-y:auto;">
                                    <p class="text-muted small mb-0">Select Garment type first...</p>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div id="sub_specsFields">
                            <p class="text-muted small mb-0">Select a garment type to see specifications.</p>
                        </div>
                    </div>

                    <!-- TAB 3: SIZES -->
                    <div class="tab-pane fade" id="sub-sizes" role="tabpanel">
                        <div class="btn-group btn-group-sm mb-3 w-100" role="group">
                            <input type="radio" class="btn-check" name="subSizeMode" id="subSizeModeByQty" value="by-qty" checked onchange="sub_toggleSizeMode()">
                            <label class="btn btn-outline-primary" for="subSizeModeByQty"><i class="fas fa-list-ol me-1"></i>By Size</label>
                            <input type="radio" class="btn-check" name="subSizeMode" id="subSizeModeRoster" value="roster" onchange="sub_toggleSizeMode()">
                            <label class="btn btn-outline-primary" for="subSizeModeRoster"><i class="fas fa-users me-1"></i>Per Person (Names)</label>
                        </div>

                        <!-- MODE 1: BY SIZE -->
                        <div id="subSizeByQty">
                            <div class="alert alert-info py-2 small">
                                <i class="fas fa-info-circle me-1"></i> Enter quantity per size. Total auto-calculated.
                            </div>
                            <div class="row g-2">
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">XS</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="XS" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Small</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="SMALL" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Medium</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="MEDIUM" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Large</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="LARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">2XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="2XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">3XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="3XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">4XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="4XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">5XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="5XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">6XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="6XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">7XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="7XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">8XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="8XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                            </div>
                        </div>

                        <!-- MODE 2: PER PERSON -->
                        <div id="subSizeRoster" style="display:none;">
                            <div class="alert alert-success py-2 small">
                                <i class="fas fa-users me-1"></i> Add each person's name and assigned size.
                            </div>
                            <div class="row g-2 mb-2 align-items-end">
                                <div class="col-2">
                                    <label class="form-label small mb-0">#</label>
                                    <input type="text" class="form-control form-control-sm" id="subRosterNewNumber" placeholder="No.">
                                </div>
                                <div class="col-4">
                                    <label class="form-label small mb-0">Name *</label>
                                    <input type="text" class="form-control form-control-sm" id="subRosterNewName" placeholder="Person's name">
                                </div>
                                <div class="col-3">
                                    <label class="form-label small mb-0">Size *</label>
                                    <select class="form-control form-control-sm" id="subRosterNewSize">
                                        <option value="">--</option>
                                        <option value="XS">XS</option>
                                        <option value="S">S</option>
                                        <option value="M">M</option>
                                        <option value="L">L</option>
                                        <option value="XL">XL</option>
                                        <option value="2XL">2XL</option>
                                        <option value="3XL">3XL</option>
                                        <option value="4XL">4XL</option>
                                        <option value="5XL">5XL</option>
                                        <option value="6XL">6XL</option>
                                        <option value="7XL">7XL</option>
                                        <option value="8XL">8XL</option>
                                    </select>
                                </div>
                                <div class="col-3">
                                    <label class="form-label small mb-0">&nbsp;</label>
                                    <button type="button" class="btn btn-success btn-sm w-100" onclick="sub_addRosterRow()">
                                        <i class="fas fa-plus"></i> Add
                                    </button>
                                </div>
                            </div>

                            <div class="mb-2">
                                <div class="d-flex gap-2 flex-wrap">
                                    <button type="button" class="btn btn-outline-secondary btn-sm" onclick="sub_toggleBulkPaste()">
                                        <i class="fas fa-paste me-1"></i>Bulk Paste List
                                    </button>
                                    <button type="button" class="btn btn-outline-primary btn-sm" onclick="document.getElementById('subExcelInput').click()">
                                        <i class="fas fa-file-excel me-1"></i>Upload Excel
                                    </button>
                                    <input type="file" id="subExcelInput" accept=".xlsx,.xls,.csv" style="display:none" onchange="sub_uploadExcel(event)">
                                </div>
                                <div id="subBulkPasteArea" style="display:none;" class="mt-2">
                                    <label class="form-label small">Paste one per line: <code>Name,Size</code> or <code>Number,Name,Size</code></label>
                                    <textarea class="form-control form-control-sm" id="subBulkPasteInput" rows="4" placeholder="e.g.&#10;MON,XL&#10;KOKO,L&#10;MANEX,XL&#10;JUN,L&#10;GERBIE,M"></textarea>
                                    <button type="button" class="btn btn-info btn-sm mt-1" onclick="sub_bulkPaste()">
                                        <i class="fas fa-upload me-1"></i>Import List
                                    </button>
                                </div>
                            </div>

                            <div class="table-responsive" style="max-height:300px;overflow-y:auto;">
                                <table class="table table-sm table-bordered mb-0" id="subRosterTable">
                                    <thead class="table-light">
                                        <tr id="subRosterHeader">
                                            <th style="width:50px">#</th>
                                            <th>Name</th>
                                            <th style="width:80px">Size</th>
                                            <th style="width:40px">Qty</th>
                                            <th style="width:40px"></th>
                                        </tr>
                                    </thead>
                                    <tbody id="subRosterBody">
                                        <tr id="subRosterEmpty">
                                            <td colspan="5" class="text-center text-muted small py-3">
                                                <i class="fas fa-user-plus me-1"></i> Add names above to build your roster.
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="mt-1 text-end">
                                <small class="text-muted"><span id="subRosterCount">0</span> people</small>
                            </div>
                        </div>
                    </div>

                    <!-- TAB 4: PRICING -->
                    <div class="tab-pane fade" id="sub-pricing-body" role="tabpanel">
                        <div class="alert alert-success py-2 small mb-2">
                            <i class="fas fa-calculator me-1"></i> <strong>Auto-computed:</strong> Pumili ng Garment, Fabric, Parts, at Sizes — kusa na lang nag-cocompute ang pricing dito.
                            <span class="d-block mt-1 text-muted">💡 Kung may <strong>Special Price</strong>, click <u>Set Special Price</u> button sa baba para mag-override ng unit price.</span>
                        </div>
                        <div class="card border-success mt-3">
                            <div class="card-header bg-success text-white small py-2">
                                <i class="fas fa-file-invoice me-1"></i> Full Price Breakdown
                            </div>
                            <div class="card-body py-2">
                                <div class="d-flex justify-content-between small">
                                    <span id="subPricing_garmentLabel">Garment:</span>
                                    <strong><span id="subPricing_garmentPrice">₱0.00</span></strong>
                                </div>
                                <div class="d-flex justify-content-between small">
                                    <span id="subPricing_fabricLabel">Fabric:</span>
                                    <strong><span id="subPricing_fabricPrice">₱0.00</span></strong>
                                </div>
                                <div id="subPricing_partsBreakdown"></div>
                                <div id="subPricing_sizeBreakdown"></div>
                                <hr class="my-1">
                                <div class="d-flex justify-content-between">
                                    <span class="fw-bold">Per Unit (base):</span>
                                    <strong class="fs-6"><span id="subPricing_unitPrice">₱0.00</span></strong>
                                </div>
                                <div class="d-flex justify-content-between small">
                                    <span>Total Qty (from Sizes tab):</span>
                                    <strong><span id="subPricing_totalQty">0</span></strong>
                                </div>
                                <hr class="my-1">
                                <div class="d-flex justify-content-between fw-bold fs-5" style="color:#198754;">
                                    <span>TOTAL:</span>
                                    <span id="subPricing_grandTotal">₱0.00</span>
                                </div>
                                <div id="subSpecialPriceIndicator" class="alert alert-warning py-1 small mb-0 mt-2" style="display:none;">
                                    <i class="fas fa-tag me-1"></i> <strong>Special Price:</strong> <span id="subSpecialPriceDisplay">₱0.00</span>/piece
                                </div>
                            </div>
                        </div>

                        <div class="mt-3 p-2 bg-light rounded" id="subSpecialPriceSection" style="display:none;">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="fw-bold small">💵 SPECIAL PRICE ACTIVE</span>
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="sub_clearSpecialPrice()">✕ Clear</button>
                            </div>
                            <div class="mb-2">
                                <label class="small text-muted">Set Price Per Piece:</label>
                                <div class="input-group input-group-sm">
                                    <span class="input-group-text">₱</span>
                                    <input type="number" class="form-control" id="subSpecialPrintTotal" min="0" step="0.01" placeholder="0.00/piece" oninput="sub_onSpecialPriceChange()">
                                </div>
                            </div>
                            <div class="mb-2">
                                <label class="small text-muted">Reason *</label>
                                <input type="text" class="form-control form-control-sm" id="subSpecialPriceReason" placeholder="Why special price?" required>
                            </div>
                        </div>

                        <button type="button" class="btn btn-outline-warning btn-sm w-100 mt-2" id="subSpecialPriceBtn" onclick="sub_toggleSpecialPrice()">
                            💰 Special Price
                        </button>

                        <button type="button" class="btn btn-success w-100 mt-2" id="subAddItemBtn" onclick="sub_addItemToOrder()">
                            <i class="fas fa-check-circle me-2"></i> Add to Order
                        </button>
                        <button type="button" class="btn btn-outline-info w-100 mt-2" id="subPrintOrderSlip" onclick="sub_printOrderSlip()">
                            <i class="fas fa-print me-2"></i> Print Order Slip
                        </button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!-- Column Mapping Modal -->
<div class="modal fade" id="subColumnMapModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h6 class="modal-title"><i class="fas fa-columns me-1"></i>Map Columns</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body py-2 small">
                <p class="mb-2 text-muted">Match your Excel columns to roster fields:</p>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Name</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_name"><option value="">-- skip --</option></select>
                </div>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Number</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_number"><option value="">-- skip --</option></select>
                </div>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Size</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_size"><option value="">-- skip --</option></select>
                </div>
                <small class="text-muted" id="subMapPreview">Loading preview...</small>
            </div>
            <div class="modal-footer py-1">
                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-sm btn-success" onclick="sub_applyMapping()">
                    <i class="fas fa-check me-1"></i>Import
                </button>
            </div>
        </div>
    </div>
</div>

<script>
// Load XLSX library if not available
if (typeof XLSX === 'undefined') {
    var script = document.createElement('script');
    script.src = 'https://cdn.sheetjs.com/xlsx-0.20.2/package/dist/xlsx.full.min.js';
    script.onload = function() { console.log('XLSX loaded for Add Product modal'); };
    document.head.appendChild(script);
}

// ======= DATA =======
window.sub_sizesData = {};
window.sub_hasSpecialPrice = false;
window.sub_excelData = null;
window.sub_excelHeaders = null;
window.sub_partsData = [];
window.sub_garmentsData = [];

// Garment spec field definitions (same as create page)
var sub_garmentSpecMap = {
    tshirt: {
        nameKeywords: ['TSHIRT'],
        fields: [
            { id: 'sub_spec_neckRibbingColor', label: 'Neck Ribbings Color', type: 'select', options: ['BLACK', 'WHITE', 'SUBILI PRINT'] },
            { id: 'sub_spec_neckTape', label: 'Neck Tape', type: 'select', options: ['NO DESIGN (STANDARD)', 'WITH DESIGN (FROM CLIENT)'], autoAddon: { 'WITH DESIGN (FROM CLIENT)': 27 } },
            { id: 'sub_spec_sizeLabel', label: 'Size Label', type: 'select', options: ['YES', 'NO'] },
            { id: 'sub_spec_cuffs', label: 'Cuffs', type: 'select', options: ['SUBILI PRINT', 'KNITTED CUFFS', 'SELF FABRIC'], autoAddon: { 'KNITTED CUFFS': 36 } },
            { id: 'sub_spec_slit', label: 'Slit', type: 'select', options: ['YES', 'NO'], autoAddon: { 'YES': 29 } },
            { id: 'sub_spec_pocket', label: 'Pocket', type: 'select', options: ['NO', 'ONE POCKET', 'TWO POCKETS'], autoAddon: { 'ONE POCKET': 30, 'TWO POCKETS': 39 } },
            { id: 'sub_spec_armsleeve', label: 'Armsleeve', type: 'select', options: ['SHORTSLEEVE', 'LONGSLEEVE'], autoAddon: { 'LONGSLEEVE': 28 } },
            { id: 'sub_spec_shoulder', label: 'Shoulder', type: 'select', options: ['REGULAR', 'RAGLAN'], autoAddon: { 'RAGLAN': 33 } }
        ]
    },
    polo: {
        nameKeywords: ['POLO'],
        fields: [
            { id: 'sub_spec_collar', label: 'Collar', type: 'select', options: ['SUBILI PRINT', 'KNITTED COLLAR'], autoAddon: { 'KNITTED COLLAR': 35 } },
            { id: 'sub_spec_cuffs', label: 'Cuffs', type: 'select', options: ['SUBILI PRINT', 'KNITTED CUFFS', 'SELF FABRIC'], autoAddon: { 'KNITTED CUFFS': 36 } },
            { id: 'sub_spec_neckTape', label: 'Neck Tape', type: 'select', options: ['NO DESIGN (STANDARD)', 'WITH DESIGN (FROM CLIENT)'], autoAddon: { 'WITH DESIGN (FROM CLIENT)': 27 } },
            { id: 'sub_spec_sizeLabel', label: 'Size Label', type: 'select', options: ['YES', 'NO'] },
            { id: 'sub_spec_slit', label: 'Slit', type: 'select', options: ['YES', 'NO'], autoAddon: { 'YES': 29 } },
            { id: 'sub_spec_pocket', label: 'Pocket', type: 'select', options: ['NO', 'ONE POCKET', 'TWO POCKETS'], autoAddon: { 'ONE POCKET': 30, 'TWO POCKETS': 39 } },
            { id: 'sub_spec_armsleeve', label: 'Armsleeve', type: 'select', options: ['SHORTSLEEVE', 'LONGSLEEVE'], autoAddon: { 'LONGSLEEVE': 28 } },
            { id: 'sub_spec_shoulder', label: 'Shoulder', type: 'select', options: ['REGULAR', 'RAGLAN'], autoAddon: { 'RAGLAN': 33 } }
        ]
    },
    jersey: {
        nameKeywords: ['JERSEY UP', 'JERSEY UP AND DOWN'],
        fields: [
            { id: 'sub_spec_neckRibbingColor', label: 'Neck Ribbings Color', type: 'select', options: ['BLACK', 'WHITE', 'SUBILI PRINT'] },
            { id: 'sub_spec_neckTape', label: 'Neck Tape', type: 'select', options: ['NO DESIGN (STANDARD)', 'WITH DESIGN (FROM CLIENT)'], autoAddon: { 'WITH DESIGN (FROM CLIENT)': 27 } },
            { id: 'sub_spec_sizeLabel', label: 'Size Label', type: 'select', options: ['YES', 'NO'] },
            { id: 'sub_spec_slit', label: 'Slit', type: 'select', options: ['YES', 'NO'], autoAddon: { 'YES': 29 } },
            { id: 'sub_spec_neckShape', label: 'Neck Shape', type: 'select', options: ['VNECK', 'ROUNDNECK'] },
            { id: 'sub_spec_cutType', label: 'Type of Cut', type: 'select', options: ['NBA CUT', 'REGULAR'], autoAddon: { 'NBA CUT': 32 } }
        ]
    },
    'jersey-short': {
        nameKeywords: ['JERSEY SHORT'],
        fields: [
            { id: 'sub_spec_inner', label: 'Inner', type: 'select', options: ['YES', 'NO'], autoAddon: { 'YES': 38 } },
            { id: 'sub_spec_pocket', label: 'Pocket', type: 'select', options: ['NO', 'ONE POCKET', 'TWO POCKETS'], autoAddon: { 'ONE POCKET': 30, 'TWO POCKETS': 39 } }
        ]
    },
    hoodie: {
        nameKeywords: ['HOODIE'],
        fields: [
            { id: 'sub_spec_neckRibbingColor', label: 'Neck Ribbings Color', type: 'select', options: ['BLACK', 'WHITE', 'SUBILI PRINT'] },
            { id: 'sub_spec_neckTape', label: 'Neck Tape', type: 'select', options: ['NO DESIGN (STANDARD)', 'WITH DESIGN (FROM CLIENT)'], autoAddon: { 'WITH DESIGN (FROM CLIENT)': 27 } },
            { id: 'sub_spec_sizeLabel', label: 'Size Label', type: 'select', options: ['YES', 'NO'] },
            { id: 'sub_spec_cuffs', label: 'Cuffs', type: 'select', options: ['SUBILI PRINT', 'KNITTED CUFFS', 'SELF FABRIC'], autoAddon: { 'KNITTED CUFFS': 36 } },
            { id: 'sub_spec_slit', label: 'Slit', type: 'select', options: ['YES', 'NO'], autoAddon: { 'YES': 29 } },
            { id: 'sub_spec_pocket', label: 'Pocket', type: 'select', options: ['NO', 'ONE POCKET', 'TWO POCKETS'], autoAddon: { 'ONE POCKET': 30, 'TWO POCKETS': 39 } },
            { id: 'sub_spec_armsleeve', label: 'Armsleeve', type: 'select', options: ['SHORTSLEEVE', 'LONGSLEEVE'], autoAddon: { 'LONGSLEEVE': 28 } },
            { id: 'sub_spec_shoulder', label: 'Shoulder', type: 'select', options: ['REGULAR', 'RAGLAN'], autoAddon: { 'RAGLAN': 33 } }
        ]
    }
};

window.sub_handleSpecAddon = function (field, selectedValue) {
    for (var val in field.autoAddon) {
        if (!field.autoAddon.hasOwnProperty(val)) continue;
        var partId = field.autoAddon[val];
        var cb = document.querySelector('.part-checkbox[value="' + partId + '"]');
        if (cb) {
            cb.checked = false;
            cb.disabled = false;
        }
    }
    if (selectedValue && field.autoAddon[selectedValue] !== undefined) {
        var targetPartId = field.autoAddon[selectedValue];
        var targetCb = document.querySelector('.part-checkbox[value="' + targetPartId + '"]');
        if (targetCb) {
            targetCb.checked = true;
            targetCb.disabled = true;
        }
    }
    sub_calculateTotal();
    sub_autoGenerateDescription();
};

// ======= OPEN =======
window.openSubAddProductModal = function(saleData) {
    // Accept saleData from kanban context (object with services, etc.)
    // or use $sale PHP variable when available
    <?php if (isset($sale)): ?>
    <?php
        $__saleServices = is_string($sale->services) ? json_decode($sale->services, true) : (array)$sale->services;
        $__customerName = $sale->customer_name ?? '';
    ?>
    // On show page — use PHP data
    var services = <?php echo json_encode($__saleServices); ?> || [];
    var customerName = <?php echo json_encode($__customerName); ?>;
    <?php else: ?>
        // On kanban — use passed saleData + modal dataset
        var services = (saleData && saleData.services) || [];
        var customerName = document.getElementById('subAddProductModal').dataset.customerName || '';
    <?php endif; ?>
    
    // Reset modal title to default
    var titleIcon = document.getElementById('subModalTitleIcon');
    if (titleIcon) { titleIcon.className = 'fas fa-box'; }
    var titleText = document.getElementById('subModalTitleText');
    if (titleText) { titleText.textContent = 'Add Fullsublimation Product'; }
    
    var projectName = document.getElementById('sub_projectName');
    projectName.value = customerName ? 'Additional Order - ' + customerName : 'Additional Order';
    
    // Auto-fill date needed with today's date (customer can adjust)
    document.getElementById('sub_dateNeeded').value = new Date().toISOString().split('T')[0];

    // Disable project name (redundant on existing order)
    projectName.disabled = true;
    projectName.readOnly = true;
    projectName.classList.add('sub-quick-disabled');
    
    // Reset everything else
    document.getElementById('sub_description').value = '';
    document.getElementById('sub_designer').value = '';
    document.getElementById('sub_notes').value = '';
    
    // Reset parts
    var partsCont = document.getElementById('sub_partsContainer');
    partsCont.innerHTML = '<p class="text-muted small mb-0">Select Garment type first...</p>';
    
    // Reset sizes
    document.querySelectorAll('.sub-size-qty').forEach(function(el) { el.value = '0'; });
    
    // Reset roster
    var rosterBody = document.getElementById('subRosterBody');
    var rows = rosterBody.querySelectorAll('tr.roster-row');
    rows.forEach(function(r) { r.remove(); });
    var empty = document.getElementById('subRosterEmpty');
    if (empty) empty.style.display = '';
    document.getElementById('subRosterCount').textContent = '0';
    
    // Reset size mode
    document.getElementById('subSizeModeByQty').checked = true;
    sub_toggleSizeMode();
    
    // Reset mockup
    sub_removeMockup();
    
    // Reset special price
    var spSec = document.getElementById('subSpecialPriceSection');
    var spBtn = document.getElementById('subSpecialPriceBtn');
    if (spSec) spSec.style.display = 'none';
    if (spBtn) { spBtn.textContent = '💰 Special Price'; spBtn.classList.remove('btn-warning'); spBtn.classList.add('btn-outline-warning'); }
    document.getElementById('subSpecialPrintTotal').value = '';
    document.getElementById('subSpecialPriceReason').value = '';
    window.sub_hasSpecialPrice = false;
    
    // Reset garment/fabric selects
    var garmentSel = document.getElementById('sub_garmentSelect');
    var fabricSel = document.getElementById('sub_fabricSelect');
    if (garmentSel) garmentSel.innerHTML = '<option value="">Loading...</option>';
    if (fabricSel) fabricSel.innerHTML = '<option value="">Loading...</option>';
    document.getElementById('sub_specsFields').innerHTML = '<p class="text-muted small mb-0">Select a garment type to see specifications.</p>';
    
    // Fetch sublimation prices
    fetch('/api/sublimation-prices')
        .then(function(r) { return r.json(); })
        .then(function(data) {
            window.sub_sizesData = {};
            window.sub_partsData = data.parts || [];
            window.sub_garmentsData = data.garments || [];
            if (data.sizes && data.sizes.length) {
                data.sizes.forEach(function(item) {
                    window.sub_sizesData[item.name.toUpperCase()] = parseFloat(item.price) || 0;
                });
            }
            // Populate garment select
            if (garmentSel) {
                garmentSel.innerHTML = '<option value="">-- Select Garment --</option>';
                data.garments.forEach(function(item) {
                    var opt = document.createElement('option');
                    opt.value = item.id || item.name;
                    opt.textContent = item.name;
                    opt.dataset.price = item.price || 0;
                    garmentSel.appendChild(opt);
                });
            }
            // Populate fabric select
            if (fabricSel) {
                fabricSel.innerHTML = '<option value="">-- Select Fabric --</option>';
                data.fabrics.forEach(function(item) {
                    var opt = document.createElement('option');
                    opt.value = item.id || item.name;
                    opt.textContent = item.name;
                    opt.dataset.price = item.price || 0;
                    fabricSel.appendChild(opt);
                });
            }
            sub_calculateTotal();
        })
        .catch(function() {
            if (garmentSel) garmentSel.innerHTML = '<option value="">Error loading</option>';
            if (fabricSel) fabricSel.innerHTML = '<option value="">Error loading</option>';
        });
    
    // Switch to first tab
    var firstTab = document.querySelector('#subSublimationTab .nav-link');
    if (firstTab && typeof bootstrap !== 'undefined') {
        var tab = new bootstrap.Tab(firstTab);
        tab.show();
    }
    
    // Set mode and reset button text
    window.sub_reprocessMode = false;
    var addBtn = document.getElementById('subAddItemBtn');
    restoreAddBtnUI(addBtn, false);
    
    // Show modal
    var modal = new bootstrap.Modal(document.getElementById('subAddProductModal'));
    modal.show();
};

/**
 * Open the sublimation modal in Reprocess mode.
 * Starts with a blank form (same as add product) but uses the reprocess endpoint.
 */
window.openSubReprocessModal = function() {
    window.sub_reprocessMode = true;
    
    // Same blank reset as add product
    <?php if (isset($sale)): ?>
    <?php
        $__customerName = $sale->customer_name ?? '';
    ?>
    var customerName = <?php echo json_encode($__customerName); ?>;
    <?php else: ?>
        var customerName = document.getElementById('subAddProductModal').dataset.customerName || '';
    <?php endif; ?>
    
    var projectName = document.getElementById('sub_projectName');
    projectName.value = customerName ? 'Reprocess Order - ' + customerName : 'Reprocess Order';
    
    // Auto-fill date needed with today's date
    document.getElementById('sub_dateNeeded').value = new Date().toISOString().split('T')[0];

    // Update modal title
    document.getElementById('subModalTitleIcon').className = 'fas fa-sync-alt';
    document.getElementById('subModalTitleText').textContent = 'Reprocess Order';
    
    // Disable project name
    projectName.disabled = true;
    projectName.readOnly = true;
    projectName.classList.add('sub-quick-disabled');
    
    // Reset everything else
    document.getElementById('sub_description').value = '';
    document.getElementById('sub_designer').value = '';
    document.getElementById('sub_notes').value = '';
    
    var partsCont = document.getElementById('sub_partsContainer');
    partsCont.innerHTML = '<p class="text-muted small mb-0">Select Garment type first...</p>';
    
    document.querySelectorAll('.sub-size-qty').forEach(function(el) { el.value = '0'; });
    
    var rosterBody = document.getElementById('subRosterBody');
    var rows = rosterBody.querySelectorAll('tr.roster-row');
    rows.forEach(function(r) { r.remove(); });
    var empty = document.getElementById('subRosterEmpty');
    if (empty) empty.style.display = '';
    document.getElementById('subRosterCount').textContent = '0';
    
    document.getElementById('subSizeModeByQty').checked = true;
    sub_toggleSizeMode();
    
    sub_removeMockup();
    
    var spSec = document.getElementById('subSpecialPriceSection');
    var spBtn = document.getElementById('subSpecialPriceBtn');
    if (spSec) spSec.style.display = 'none';
    if (spBtn) { spBtn.textContent = '💰 Special Price'; spBtn.classList.remove('btn-warning'); spBtn.classList.add('btn-outline-warning'); }
    document.getElementById('subSpecialPrintTotal').value = '';
    document.getElementById('subSpecialPriceReason').value = '';
    window.sub_hasSpecialPrice = false;
    
    // Reset garment/fabric & specs
    var garmentSel = document.getElementById('sub_garmentSelect');
    var fabricSel = document.getElementById('sub_fabricSelect');
    if (garmentSel) garmentSel.innerHTML = '<option value="">Loading...</option>';
    if (fabricSel) fabricSel.innerHTML = '<option value="">Loading...</option>';
    document.getElementById('sub_specsFields').innerHTML = '<p class="text-muted small mb-0">Select a garment type to see specifications.</p>';
    
    // Change save button text
    var addBtn = document.getElementById('subAddItemBtn');
    if (addBtn) {
        addBtn.innerHTML = '<i class="fas fa-sync-alt me-2"></i> Submit Reprocess';
        addBtn.classList.remove('btn-success');
        addBtn.classList.add('btn-warning');
    }
    
    // Fetch sublimation prices (same as add product)
    fetch('/api/sublimation-prices')
        .then(function(r) { return r.json(); })
        .then(function(data) {
            window.sub_sizesData = {};
            window.sub_partsData = data.parts || [];
            window.sub_garmentsData = data.garments || [];
            if (data.sizes && data.sizes.length) {
                data.sizes.forEach(function(item) {
                    window.sub_sizesData[item.name.toUpperCase()] = parseFloat(item.price) || 0;
                });
            }
            if (garmentSel) {
                garmentSel.innerHTML = '<option value="">-- Select Garment --</option>';
                data.garments.forEach(function(item) {
                    var opt = document.createElement('option');
                    opt.value = item.id || item.name;
                    opt.textContent = item.name;
                    opt.dataset.price = item.price || 0;
                    garmentSel.appendChild(opt);
                });
            }
            if (fabricSel) {
                fabricSel.innerHTML = '<option value="">-- Select Fabric --</option>';
                if (data.fabrics && data.fabrics.length) {
                    data.fabrics.forEach(function(item) {
                        var opt = document.createElement('option');
                        opt.value = item.id || item.name;
                        opt.textContent = item.name;
                        opt.dataset.price = item.price || 0;
                        fabricSel.appendChild(opt);
                    });
                }
            }
            // Reset pricing
            document.getElementById('subPricing_totalQty').textContent = '0';
            document.getElementById('subPricing_unitPrice').textContent = '₱0.00';
            document.getElementById('subPricing_grandTotal').textContent = '₱0.00';
            var szSec = document.getElementById('subPricing_sizesSection');
            if (szSec) szSec.style.display = 'none';
            var szGrid = document.getElementById('sub_sizeQtyGrid');
            if (szGrid) szGrid.style.display = 'none';
            window.sub_selectedGarment = null;
            // Select a size-eligible (non-'sizing') garment by default so sizes show (add product only)
            if (!window.sub_reprocessMode) {
                sub_initDefaultGarment();
            }
        })
        .catch(function(err) {
            console.error('Failed to load sublimation prices:', err);
        });
    
    // Show modal
    var modal = new bootstrap.Modal(document.getElementById('subAddProductModal'));
    modal.show();
};

// ======= MOCKUP =======
window.sub_previewMockup = function(event) {
    var file = event.target.files[0];
    if (!file) return;
    var reader = new FileReader();
    reader.onload = function(e) {
        document.getElementById('subMockupPreview').src = e.target.result;
        document.getElementById('subMockupPreview').style.display = 'block';
        document.getElementById('subMockupPlaceholder').style.display = 'none';
        document.getElementById('subMockupFileInfo').style.display = 'block';
        document.getElementById('subMockupFileName').textContent = file.name;
    };
    reader.readAsDataURL(file);
};

window.sub_removeMockup = function() {
    document.getElementById('subMockupPreview').src = '';
    document.getElementById('subMockupPreview').style.display = 'none';
    document.getElementById('subMockupPlaceholder').style.display = '';
    document.getElementById('subMockupFileInfo').style.display = 'none';
    document.getElementById('subMockupUpload').value = '';
};

// ======= DESCRIPTION =======
window.sub_autoGenerateDescription = function() {
    var garment = document.getElementById('sub_garmentSelect');
    var fabric = document.getElementById('sub_fabricSelect');
    var partsData = window.sub_partsData || [];
    var parts = [];
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        var partId = parseInt(cb.value) || cb.value;
        var found = partsData.find(function(p) { return parseInt(p.id) === parseInt(partId); });
        parts.push(found ? found.name : partId);
    });
    var garmentText = garment.options[garment.selectedIndex] ? garment.options[garment.selectedIndex].text : '';
    var fabricText = fabric.options[fabric.selectedIndex] ? fabric.options[fabric.selectedIndex].text : '';
    var desc = '';
    if (garmentText) desc += garmentText;
    if (fabricText) desc += (desc ? ' - ' : '') + fabricText;
    if (parts.length) desc += (desc ? ' | ' : '') + parts.join('+');
    document.getElementById('sub_description').value = desc;
};

/**
 * Select the first 'sized' garment (not a 'sizing' variant) so sizes section shows.
 */
window.sub_initDefaultGarment = function() {
    var sel = document.getElementById('sub_garmentSelect');
    if (!sel || sel.options.length <= 1) return;
    // Skip the first placeholder option, pick the first real garment
    sel.selectedIndex = 1;
    sub_renderSpecs();
    sub_calculateTotal();
    sub_autoGenerateDescription();
};

// ======= SPECS RENDER =======
window.sub_renderSpecs = function() {
    var select = document.getElementById('sub_garmentSelect');
    var container = document.getElementById('sub_specsFields');
    var partsCont = document.getElementById('sub_partsContainer');
    var garmentId = select.value;
    
    if (!garmentId) {
        container.innerHTML = '<p class="text-muted small mb-0">Select a garment type to see specifications.</p>';
        partsCont.innerHTML = '<p class="text-muted small mb-0">Select Garment type first...</p>';
        return;
    }
    
    var garmentName = select.options[select.selectedIndex].textContent;
    var upperName = garmentName.toUpperCase();
    
    // Find matching spec group
    var matchingGroup = null;
    for (var key in sub_garmentSpecMap) {
        if (!sub_garmentSpecMap.hasOwnProperty(key)) continue;
        var group = sub_garmentSpecMap[key];
        for (var kwIdx = 0; kwIdx < group.nameKeywords.length; kwIdx++) {
            if (upperName.indexOf(group.nameKeywords[kwIdx].toUpperCase()) !== -1) {
                matchingGroup = group;
                break;
            }
        }
        if (matchingGroup) break;
    }
    
    // Render spec fields
    if (matchingGroup) {
        var html = '<div class="spec-fields-container">';
        matchingGroup.fields.forEach(function(f) {
            html += '<div class="d-flex align-items-center mb-2 p-2 rounded" style="background:#f8f9fa;border:1px solid #e9ecef;">';
            html += '<label class="form-label small fw-semibold mb-0 me-2" style="min-width:110px;white-space:nowrap;">' + f.label + '</label>';
            html += '<div class="flex-grow-1">';
            if (f.type === 'select') {
                html += '<select class="form-control form-control-sm sub-spec-select" data-fid="' + f.id + '">';
                html += '<option value="">-- Select --</option>';
                for (var oo = 0; oo < f.options.length; oo++) {
                    html += '<option value="' + f.options[oo] + '">' + f.options[oo] + '</option>';
                }
                html += '</select>';
            }
            html += '</div></div>';
        });
        html += '</div>';
        container.innerHTML = html;
        
        // Wire up auto-addon change handlers
        matchingGroup.fields.forEach(function(f) {
            if (!f.autoAddon) return;
            var sel = container.querySelector('.sub-spec-select[data-fid="' + f.id + '"]');
            if (!sel) return;
            (function(field) {
                sel.onchange = function() {
                    sub_handleSpecAddon(field, this.value);
                };
            })(f);
        });
    } else {
        container.innerHTML = '<p class="text-muted small mb-0">No specific fields for this garment type.</p>';
    }
    
    // Render parts checkboxes from cached parts data
    var parts = window.sub_partsData || [];
    if (parts.length) {
        var partsHtml = '';
        parts.forEach(function(part, idx) {
            var pName = part.name || '';
            var pPrice = parseFloat(part.price || 0);
            var pId = part.id || idx;
            partsHtml += '<div class="form-check form-check-inline">';
            partsHtml += '<input class="form-check-input part-checkbox" type="checkbox" id="sub_part_' + idx + '" value="' + pId + '" data-price="' + pPrice + '" onchange="sub_calculateTotal(); sub_autoGenerateDescription()">';
            partsHtml += '<label class="form-check-label small" for="sub_part_' + idx + '">' + pName + ' (₱' + pPrice.toFixed(2) + ')</label>';
            partsHtml += '</div>';
        });
        partsCont.innerHTML = partsHtml;
    } else {
        partsCont.innerHTML = '<p class="text-muted small mb-0">No additional parts available.</p>';
    }
};

// ======= PRICE CALC =======
// Helper: flexible size name match (form uses 5XLARGE, pricing may use 5XL)
function sub_getSizePrice(name) {
    if (window.sub_sizesData[name] !== undefined) return window.sub_sizesData[name];
    if (name.endsWith('ARGE')) {
        var alt = name.slice(0, -4);
        if (window.sub_sizesData[alt] !== undefined) return window.sub_sizesData[alt];
    }
    if (name.endsWith('LARGE')) {
        var alt2 = name.slice(0, -5);
        if (window.sub_sizesData[alt2] !== undefined) return window.sub_sizesData[alt2];
    }
    return 0;
}

window.sub_calculateTotal = function() {
    var garmentSelect = document.getElementById('sub_garmentSelect');
    var fabricSelect = document.getElementById('sub_fabricSelect');
    var sizeInputs = document.querySelectorAll('.sub-size-qty');
    var rosterRows = document.querySelectorAll('#subRosterBody tr.roster-row');
    
    var garmentPrice = 0, fabricPrice = 0, partsPrice = 0, sizeAddon = 0;
    
    // Garment price
    if (garmentSelect.selectedIndex > 0) {
        garmentPrice = parseFloat(garmentSelect.options[garmentSelect.selectedIndex].dataset.price) || 0;
    }
    
    // Fabric price
    if (fabricSelect.selectedIndex > 0) {
        fabricPrice = parseFloat(fabricSelect.options[fabricSelect.selectedIndex].dataset.price) || 0;
    }
    
    // Parts
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        partsPrice += parseFloat(cb.dataset.price) || 0;
    });
    
    // Sizes - count total qty and get size addons
    var totalQty = 0;
    var sizeBreakdownHtml = '';
    
    // Check which mode is active
    var isRoster = document.getElementById('subSizeModeRoster') && document.getElementById('subSizeModeRoster').checked;
    
    if (isRoster) {
        // Sum roster rows + generate size breakdown
        var rosterSizeCounts = {};
        rosterRows.forEach(function(row) {
            var qtyInput = row.querySelector('.roster-number');
            var qty = parseInt(qtyInput ? qtyInput.value : '') || 1;
            totalQty += qty;
            
            var sizeInput = row.querySelector('.roster-size');
            if (sizeInput) {
                var sizeName = (sizeInput.value || sizeInput.textContent || '').trim().toUpperCase();
                var szPrice = sub_getSizePrice(sizeName);
                if (szPrice > 0) {
                    if (!rosterSizeCounts[sizeName]) rosterSizeCounts[sizeName] = {qty:0, price:szPrice};
                    rosterSizeCounts[sizeName].qty += qty;
                }
            }
        });
        
        var hasSizeDiff = false;
        Object.keys(rosterSizeCounts).sort(function(a,b) {
            var order = {XS:0,SMALL:1,MEDIUM:2,LARGE:3,XLARGE:4,'2XLARGE':5,'3XLARGE':6,'4XLARGE':7,'5XLARGE':8,'6XLARGE':9,'7XLARGE':10,'8XLARGE':11,'5XL':8,'6XL':9,'7XL':10,'8XL':11};
            return (order[a] || 99) - (order[b] || 99);
        }).forEach(function(size) {
            var info = rosterSizeCounts[size];
            if (info.price > 0) {
                hasSizeDiff = true;
                sizeBreakdownHtml += '<div class="d-flex justify-content-between small text-muted"><span>' + size + ' x' + info.qty + '</span><span>+₱' + (info.price * info.qty).toFixed(2) + '</span></div>';
            }
        });
        if (hasSizeDiff) {
            sizeBreakdownHtml = '<hr class="my-1"><div class="small fw-bold text-muted">Size Add-ons:</div>' + sizeBreakdownHtml;
        }
    } else {
        sizeInputs.forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                var size = input.dataset.size;
                var sizePrice = sub_getSizePrice(size);
                sizeAddon += sizePrice * val;
                totalQty += val;
            }
        });
        
        // Show size breakdown
        var hasSizeDiff = false;
        sizeInputs.forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                var size = input.dataset.size;
                var sizePrice = sub_getSizePrice(size);
                if (sizePrice > 0) {
                    hasSizeDiff = true;
                    sizeBreakdownHtml += '<div class="d-flex justify-content-between small text-muted"><span>' + size + ' x' + val + '</span><span>+₱' + (sizePrice * val).toFixed(2) + '</span></div>';
                }
            }
        });
        if (hasSizeDiff) {
            sizeBreakdownHtml = '<hr class="my-1"><div class="small fw-bold text-muted">Size Add-ons:</div>' + sizeBreakdownHtml;
        }
    }
    
    var baseUnit = garmentPrice + fabricPrice + partsPrice;
    var maxSizeAddon = 0;
    // Calculate maxSizeAddon from size mode inputs or roster row sizes
    if (isRoster) {
        rosterRows.forEach(function(row) {
            var sizeInput = row.querySelector('.roster-size');
            if (sizeInput) {
                var sizeName = (sizeInput.value || sizeInput.textContent || '').trim().toUpperCase();
                var szPrice = sub_getSizePrice(sizeName);
                if (szPrice > maxSizeAddon) maxSizeAddon = szPrice;
            }
        });
    } else {
        sizeInputs.forEach(function(input) {
            var size = input.dataset.size;
            var sizePrice = sub_getSizePrice(size);
            if (sizePrice > maxSizeAddon) maxSizeAddon = sizePrice;
        });
    }
    
    var unitPrice = baseUnit + maxSizeAddon;
    if (window.sub_hasSpecialPrice) {
        var spVal = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
        if (spVal > 0) unitPrice = spVal;
    }
    
    var grandTotal = unitPrice * totalQty;
    
    // Update UI
    document.getElementById('subPricing_garmentPrice').textContent = '₱' + garmentPrice.toFixed(2);
    document.getElementById('subPricing_fabricPrice').textContent = '₱' + fabricPrice.toFixed(2);
    
    var partsHtml = '';
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        var label = cb.parentElement.querySelector('label');
        var price = parseFloat(cb.dataset.price) || 0;
        partsHtml += '<div class="d-flex justify-content-between small"><span>' + label.textContent + '</span><strong>+₱' + price.toFixed(2) + '</strong></div>';
    });
    if (partsHtml) {
        partsHtml = '<div class="d-flex justify-content-between small"><span>Parts:</span></div>' + partsHtml;
    }
    document.getElementById('subPricing_partsBreakdown').innerHTML = partsHtml;
    document.getElementById('subPricing_sizeBreakdown').innerHTML = sizeBreakdownHtml;
    document.getElementById('subPricing_unitPrice').textContent = '₱' + unitPrice.toFixed(2);
    document.getElementById('subPricing_totalQty').textContent = totalQty;
    document.getElementById('subPricing_grandTotal').textContent = '₱' + grandTotal.toFixed(2);
    
    // Update special price display
    if (window.sub_hasSpecialPrice) {
        document.getElementById('subSpecialPriceDisplay').textContent = '₱' + unitPrice.toFixed(2);
    }
};

// ======= SPECIAL PRICE =======
window.sub_toggleSpecialPrice = function() {
    var section = document.getElementById('subSpecialPriceSection');
    var btn = document.getElementById('subSpecialPriceBtn');
    if (section.style.display === 'none') {
        section.style.display = 'block';
        btn.textContent = '✕ Cancel Special Price';
        btn.classList.remove('btn-outline-warning');
        btn.classList.add('btn-warning');
    } else {
        sub_clearSpecialPrice();
    }
};

window.sub_clearSpecialPrice = function() {
    document.getElementById('subSpecialPriceSection').style.display = 'none';
    document.getElementById('subSpecialPrintTotal').value = '';
    document.getElementById('subSpecialPriceReason').value = '';
    document.getElementById('subSpecialPriceIndicator').style.display = 'none';
    var btn = document.getElementById('subSpecialPriceBtn');
    btn.textContent = '💰 Special Price';
    btn.classList.remove('btn-warning');
    btn.classList.add('btn-outline-warning');
    window.sub_hasSpecialPrice = false;
    sub_calculateTotal();
};

window.sub_onSpecialPriceChange = function() {
    var val = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
    if (val > 0) {
        window.sub_hasSpecialPrice = true;
        document.getElementById('subSpecialPriceIndicator').style.display = '';
        sub_calculateTotal();
    }
};

// ======= SIZE MODE =======
window.sub_toggleSizeMode = function() {
    var isRoster = document.getElementById('subSizeModeRoster').checked;
    document.getElementById('subSizeByQty').style.display = isRoster ? 'none' : '';
    document.getElementById('subSizeRoster').style.display = isRoster ? '' : 'none';
    sub_calculateTotal();
};

// ======= ROSTER =======
window.sub_addRosterRow = function() {
    var numberEl = document.getElementById('subRosterNewNumber');
    var nameEl = document.getElementById('subRosterNewName');
    var sizeEl = document.getElementById('subRosterNewSize');
    var name = nameEl.value.trim();
    var size = sizeEl.value;
    
    if (!name || !size) { alert('Please enter Name and Size.'); return; }
    
    var emptyRow = document.getElementById('subRosterEmpty');
    if (emptyRow) emptyRow.style.display = 'none';
    
    var tbody = document.getElementById('subRosterBody');
    var count = tbody.querySelectorAll('tr.roster-row').length + 1;
    var tr = document.createElement('tr');
    tr.className = 'roster-row';
    tr.innerHTML = '<td>' + count + '</td>' +
        '<td>' + name + '<input type="hidden" class="roster-name" value="' + name.replace(/"/g, '&quot;') + '"></td>' +
        '<td>' + size + '<input type="hidden" class="roster-size" value="' + size + '"></td>' +
        '<td>1</td>' +
        '<td><button type="button" class="btn btn-sm btn-outline-danger py-0 px-1" onclick="sub_removeRosterRow(this)"><i class="fas fa-times"></i></button></td>';
    tbody.appendChild(tr);
    
    nameEl.value = '';
    sizeEl.selectedIndex = 0;
    sub_updateRosterCount();
    sub_calculateTotal();
};

window.sub_removeRosterRow = function(btn) {
    var tr = btn.closest('tr');
    tr.remove();
    // Renumber
    var tbody = document.getElementById('subRosterBody');
    tbody.querySelectorAll('tr.roster-row').forEach(function(row, idx) {
        row.cells[0].textContent = idx + 1;
    });
    if (tbody.querySelectorAll('tr.roster-row').length === 0) {
        document.getElementById('subRosterEmpty').style.display = '';
    }
    sub_updateRosterCount();
    sub_calculateTotal();
};

window.sub_updateRosterCount = function() {
    var count = document.querySelectorAll('#subRosterBody tr.roster-row').length;
    document.getElementById('subRosterCount').textContent = count;
};

window.sub_toggleBulkPaste = function() {
    var area = document.getElementById('subBulkPasteArea');
    area.style.display = area.style.display === 'none' ? 'block' : 'none';
};

window.sub_bulkPaste = function() {
    var text = document.getElementById('subBulkPasteInput').value.trim();
    if (!text) { alert('Please paste a list first.'); return; }
    var lines = text.split('\n').filter(function(l) { return l.trim(); });
    
    lines.forEach(function(line) {
        var parts = line.split(',').map(function(p) { return p.trim(); });
        var name, size;
        if (parts.length === 2) {
            name = parts[0]; size = parts[1];
        } else if (parts.length >= 3) {
            name = parts[1]; size = parts[2];
        } else return;
        
        document.getElementById('subRosterNewName').value = name;
        var sizeSelect = document.getElementById('subRosterNewSize');
        for (var i = 0; i < sizeSelect.options.length; i++) {
            if (sizeSelect.options[i].value.toUpperCase() === size.toUpperCase()) {
                sizeSelect.selectedIndex = i;
                break;
            }
        }
        sub_addRosterRow();
    });
    document.getElementById('subBulkPasteInput').value = '';
    document.getElementById('subBulkPasteArea').style.display = 'none';
};

// ======= EXCEL =======
function _escHtml(str) {
    return String(str).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
function _normalizeSize(s) {
    var map = {xs:'XS',s:'S',m:'M',l:'L',xl:'XL','2xl':'2XL','3xl':'3XL','4xl':'4XL','5xl':'5XL','6xl':'6XL','7xl':'7XL','8xl':'8XL',sm:'SMALL',md:'MEDIUM',lg:'LARGE'};
    return map[s.toLowerCase()] || s.toUpperCase();
}

window.sub_autoBuildFromExcel = function(headers, rows) {
    // Store for mapping reference
    window.sub_excelHeaders = headers;
    window.sub_excelData = {headers: headers, rows: rows};
    
    var tbody = document.getElementById('subRosterBody');
    var theadRow = document.getElementById('subRosterHeader');
    
    // Auto-detect column roles
    var nameCols = [];
    var sizeCol = -1;
    var numCol = -1;
    
    headers.forEach(function(h, idx) {
        var hl = (h || '').toLowerCase().trim();
        if (hl.indexOf('name') >= 0 || hl === 'person' || hl === 'player' || hl === 'employee') {
            nameCols.push(idx);
        } else if (hl === 'size' || hl === 'sizes') {
            sizeCol = idx;
        }
    });
    headers.forEach(function(h, idx) {
        var hl = (h || '').toLowerCase().trim();
        if ((hl === 'qty' || hl === 'quantity' || hl === 'count') && numCol < 0) {
            numCol = idx;
        }
    });
    if (numCol < 0) {
        headers.forEach(function(h, idx) {
            var hl = (h || '').toLowerCase().trim();
            if ((hl === 'number' || hl === 'no' || hl === 'no.' || hl === '#' || hl === 'jersey') && numCol < 0) {
                numCol = idx;
            }
        });
    }
    
    // Build displayCols — ALL columns preserved, with cssClass for auto-detected roles
    var displayCols = [];
    headers.forEach(function(h, idx) {
        var cssClass = '';
        if (nameCols.indexOf(idx) >= 0) cssClass = 'roster-name';
        else if (idx === sizeCol) cssClass = 'roster-size';
        else if (idx === numCol) cssClass = 'roster-number';
        displayCols.push({header: _escHtml(h || ('(Col ' + (idx + 1) + ')')), colIdx: idx, cssClass: cssClass});
    });
    
    // Clear existing rows
    tbody.innerHTML = '';
    var empty = document.getElementById('subRosterEmpty');
    if (empty) empty.style.display = 'none';
    
    // Rebuild header with ALL Excel columns + fixed #, Qty, Remove
    var headerHtml = '<th style="width:50px">#</th>';
    displayCols.forEach(function(col) {
        headerHtml += '<th>' + col.header + '</th>';
    });
    headerHtml += '<th style="width:40px"></th>';
    theadRow.innerHTML = headerHtml;
    
    var added = 0;
    rows.forEach(function(row) {
        // Skip empty rows
        var hasData = false;
        for (var ci = 0; ci < row.length; ci++) {
            if (row[ci] !== undefined && row[ci] !== null && String(row[ci]).trim() !== '') {
                hasData = true;
                break;
            }
        }
        if (!hasData) return;
        
        var tr = document.createElement('tr');
        tr.className = 'roster-row';
        
        var cellsHtml = '<td class="text-center align-middle">' + (added + 1) + '</td>';
        
        displayCols.forEach(function(col) {
            var rawVal = (col.colIdx >= 0 && row[col.colIdx] !== undefined && row[col.colIdx] !== null)
                ? String(row[col.colIdx]).trim() : '';
            
            var displayVal = rawVal;
            if (col.cssClass === 'roster-size') {
                displayVal = _normalizeSize(displayVal);
            } else if (col.cssClass === 'roster-number') {
                var numParsed = parseFloat(displayVal);
                if (!isNaN(numParsed) && String(numParsed) === displayVal) {
                    displayVal = String(numParsed);
                } else {
                    displayVal = displayVal.replace(/\.0+$/, '');
                }
            }
            
            cellsHtml += '<td class="align-middle">' + _escHtml(displayVal);
            cellsHtml += '<input type="hidden" class="' + col.cssClass + '" data-header="' + col.header + '" value="' + _escHtml(displayVal) + '">';
            cellsHtml += '</td>';
        });
        
        cellsHtml += '<td class="text-center align-middle"><button type="button" class="btn btn-sm btn-outline-danger py-0 px-1" onclick="sub_removeRosterRow(this)" title="Remove"><i class="fas fa-times"></i></button></td>';
        
        tr.innerHTML = cellsHtml;
        tbody.appendChild(tr);
        added++;
    });
    
    if (added === 0 && empty) {
        tbody.appendChild(empty);
        empty.style.display = '';
        empty.querySelector('td').colSpan = displayCols.length + 2;
    }
    
    sub_updateRosterCount();
    sub_calculateTotal();
    
    // Switch to roster mode
    document.getElementById('subSizeModeRoster').checked = true;
    sub_toggleSizeMode();
    
    // Reset file input
    var input = document.getElementById('subExcelInput');
    if (input) input.value = '';
};

window.sub_uploadExcel = function(event) {
    var file = event.target.files[0];
    if (!file) return;
    
    function loadAndParse() {
        var reader = new FileReader();
        reader.onload = function(e) {
            try {
                var data = new Uint8Array(e.target.result);
                var workbook = XLSX.read(data, {type: 'array'});
                var firstSheet = workbook.Sheets[workbook.SheetNames[0]];
                var json = XLSX.utils.sheet_to_json(firstSheet, {header: 1, defval: ''});
                
                if (json.length < 1) {
                    alert('Excel file is empty.');
                    return;
                }
                
                var headers = json[0].map(function(h) { return String(h).trim(); });
                var rows = json.slice(1).filter(function(r) {
                    return r.some(function(cell) { return String(cell).trim() !== ''; });
                });
                
                if (rows.length < 1) {
                    alert('No data rows found (header only).');
                    return;
                }
                
                sub_autoBuildFromExcel(headers, rows);
                
            } catch(err) {
                alert('Error reading file: ' + err.message);
            }
        };
        reader.readAsArrayBuffer(file);
    }
    
    // Load SheetJS if needed
    if (typeof XLSX === 'undefined') {
        var script = document.createElement('script');
        script.src = 'https://cdn.sheetjs.com/xlsx-0.20.2/package/dist/xlsx.full.min.js';
        script.onload = loadAndParse;
        script.onerror = function() {
            var script2 = document.createElement('script');
            script2.src = 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';
            script2.onload = loadAndParse;
            script2.onerror = function() {
                alert('Failed to load Excel parser. Check internet connection.');
            };
            document.head.appendChild(script2);
        };
        document.head.appendChild(script);
    } else {
        loadAndParse();
    }
};

window.sub_applyMapping = function() {
    var rows = window.sub_excelData;
    var headers = window.sub_excelHeaders;
    if (!rows || !rows.length) { alert('No data. Please upload an Excel file first.'); return; }
    if (!headers || !headers.length) { alert('No headers found.'); return; }
    sub_autoBuildFromExcel(headers, rows);
    bootstrap.Modal.getInstance(document.getElementById('subColumnMapModal')).hide();
};

// ======= ADD TO ORDER =======
// Helper to restore button UI after error
function restoreAddBtnUI(btn, isReprocess) {
    if (!btn) return;
    if (isReprocess) {
        btn.innerHTML = '<i class="fas fa-sync-alt me-2"></i> Submit Reprocess';
        btn.classList.remove('btn-success');
        btn.classList.add('btn-warning');
    } else {
        btn.innerHTML = '<i class="fas fa-check-circle me-2"></i> Add to Order';
        btn.classList.remove('btn-warning');
        btn.classList.add('btn-success');
    }
}

window.sub_addItemToOrder = function() {
    var projectName = document.getElementById('sub_projectName').value.trim();
    var designer = document.getElementById('sub_designer').value.trim();
    var dateNeeded = document.getElementById('sub_dateNeeded').value;
    var garment = document.getElementById('sub_garmentSelect');
    var fabric = document.getElementById('sub_fabricSelect');
    
    if (!projectName) { alert('Please enter Project Name.'); return; }
    if (!designer) { alert('Please enter Designer name.'); return; }
    if (!dateNeeded) { alert('Please select Date Needed.'); return; }
    if (garment.selectedIndex <= 0) { alert('Please select a Garment Type.'); return; }
    
    // Get sizes
    var sizes = [];
    var isRoster = document.getElementById('subSizeModeRoster').checked;
    
    if (isRoster) {
        document.querySelectorAll('#subRosterBody tr.roster-row').forEach(function(row) {
            var name = row.querySelector('.roster-name');
            var size = row.querySelector('.roster-size');
            var number = row.querySelector('.roster-number');
            if (name && size) {
                // Use qty=1 for manual additions; for Excel imports, use number column value
                var qty = number ? (parseInt(number.value) || 1) : 1;
                // Extract ALL Excel columns from the roster row (preserves headers for print-slip)
                var columns = [];
                row.querySelectorAll('input[type="hidden"]').forEach(function(input) {
                    var header = input.getAttribute('data-header');
                    if (header) {
                        columns.push([header, input.value]);
                    }
                });
                var entry = {name: name.value, size: size.value, number: number ? number.value : '', qty: qty};
                if (columns.length > 0) {
                    entry.columns = columns;
                }
                sizes.push(entry);
            }
        });
    } else {
        document.querySelectorAll('.sub-size-qty').forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                sizes.push({size: input.dataset.size, qty: val});
            }
        });
    }
    
    if (sizes.length === 0) { alert('Please enter at least one size/quantity.'); return; }
    
    // Get specs from fields
    // Get specs from fields — spec fields are wrapped in .d-flex (not .col-md-6)
    var specs = {};
    document.querySelectorAll('#sub_specsFields input, #sub_specsFields select').forEach(function(el) {
        var label = el.closest('.d-flex');
        if (label) {
            var lbl = label.querySelector('.form-label');
            // Normalize spec keys to lowercase for consistent DB storage
            if (lbl) specs[lbl.textContent.replace(':', '').trim().toLowerCase()] = el.value;
        }
    });
    
    // Get parts — use actual part name from partsData instead of numeric ID
    var parts = [];
    var partsData = window.sub_partsData || [];
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        var partId = parseInt(cb.value) || cb.value;
        var found = partsData.find(function(p) { return parseInt(p.id) === parseInt(partId); });
        parts.push({
            name: found ? found.name : cb.value,
            price: parseFloat(cb.dataset.price) || 0
        });
    });
    
    var garmentName = garment.options[garment.selectedIndex].textContent;
    var fabricName = fabric.selectedIndex > 0 ? fabric.options[fabric.selectedIndex].textContent : '';
    
    // Unit price
    var unitPrice = parseFloat(document.getElementById('subPricing_unitPrice').textContent.replace('₱', '').replace(',', '')) || 0;
    var totalQty = parseInt(document.getElementById('subPricing_totalQty').textContent) || 0;
    var grandTotal = parseFloat(document.getElementById('subPricing_grandTotal').textContent.replace('₱', '').replace(',', '')) || 0;
    
    // Mockup (convert to base64 if uploaded) — also set at item top level for print slip
    var mockupData = '';
    var mockupImg = document.getElementById('subMockupPreview');
    if (mockupImg.style.display !== 'none' && mockupImg.src) {
        mockupData = mockupImg.src;
    }
    
    // Build item data — mockup set at item level too for print slip compatibility
    var item = {
        name: projectName,
        productType: 'fullsublimation',
        department: '{{ isset($sale) ? ($sale->department_code ?? $sale->department_name ?? 'class') : '' }}',
        mockup: mockupData,
        mockupUrl: mockupData,
        sublimationForm: {
            projectName: projectName,
            description: document.getElementById('sub_description').value,
            garmentType: garmentName,
            garmentId: garment.value,
            fabric: fabricName,
            fabricId: fabric.options[fabric.selectedIndex] ? fabric.options[fabric.selectedIndex].value : '',
            designer: designer,
            dateNeeded: dateNeeded,
            notes: document.getElementById('sub_notes').value,
            sizes: sizes,
            parts: parts,
            specs: specs,
            unitPrice: unitPrice,
            totalQty: totalQty,
            totalPrice: grandTotal,
            rosterMode: isRoster,
            mockup: mockupData,
            mockupUrl: mockupData
        },
        quantity: totalQty,
        unitPrice: unitPrice,
        totalPrice: grandTotal
    };
    
    // Apply special price if active
    var sps = document.getElementById('subSpecialPriceSection');
    if (sps.style.display !== 'none') {
        var spReason = document.getElementById('subSpecialPriceReason').value.trim();
        var spVal = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
        if (spVal > 0 && !spReason) { alert('Please provide a reason for the special price.'); return; }
        if (spVal > 0) {
            item.sublimationForm.specialPrice = { price: spVal, reason: spReason };
        }
    }
    
    // Submit
    var btn = document.getElementById('subAddItemBtn');
    btn.disabled = true;
    
    var isReprocess = window.sub_reprocessMode === true;
    var submitText = isReprocess ? 'Submitting Reprocess...' : 'Adding...';
    btn.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i> ' + submitText;
    
    var addProductUrl = '{{ isset($sale) ? route("sales.prototype.add-product", $sale->id) : "" }}';
    var reprocessUrl = '{{ isset($sale) ? route("sales.prototype.reprocess-order", $sale->id) : "" }}';
    var submitUrl = isReprocess ? reprocessUrl : addProductUrl;
    // Fallback for kanban: use data attribute set by JS
    if (!submitUrl) {
        submitUrl = document.getElementById('subAddProductModal').dataset.addProductUrl || '';
    }
    fetch(submitUrl, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify(item)
    })
    .then(function(r) { return r.json(); })
    .then(function(data) {
        if (data.success) {
            // Close modal
            var modalEl = document.getElementById('subAddProductModal');
            var bsModal = bootstrap.Modal.getInstance(modalEl);
            if (bsModal) bsModal.hide();
            btn.disabled = false;
            if (isReprocess) {
                btn.innerHTML = '<i class="fas fa-sync-alt me-2"></i> Submit Reprocess';
                btn.classList.remove('btn-success');
                btn.classList.add('btn-warning');
            } else {
                btn.innerHTML = '<i class="fas fa-check-circle me-2"></i> Add to Order';
            }
            // Show success toast + reload to show pending changes
            var successMsg = isReprocess ? (data.message || 'Reprocess submitted! Waiting for Manager approval.') : 'Product submitted! Waiting for Manager approval.';
            if (typeof showToast === 'function') {
                showToast(successMsg, 'success');
            } else {
                alert(successMsg);
            }
            setTimeout(function() { location.reload(); }, 1500);
        } else {
            alert('Error: ' + (data.message || 'Unknown error'));
            btn.disabled = false;
            restoreAddBtnUI(btn, isReprocess);
        }
    })
    .catch(function(err) {
        alert('Network error: ' + err.message);
        btn.disabled = false;
        restoreAddBtnUI(btn, isReprocess);
    });
};

</script>
<!-- ======= PRINT ORDER SLIP (hidden, CUSTOMER FORM SPECIFICATIONS format) ======= -->
<div id="subPrintSlip" style="display:none;">
    <style>
        @media print {
            @page { size: A4 landscape; margin: 12mm 15mm; }
            body * { visibility: hidden; }
            #subPrintSlip, #subPrintSlip * { visibility: visible; }
            #subPrintSlip { position: absolute; left: 0; top: 0; width: 100%; max-width: 277mm; display: block !important; }
            .no-print { display: none !important; }
        }
        .sub-print-slip { font-family: 'Courier New', monospace; font-size: 10pt; color: #000; width: 100%; }
        .sub-print-slip h1 { font-size: 16pt; margin: 0; text-align: center; }
        .sub-print-slip table { width: 100%; border-collapse: collapse; }
        .sub-print-slip td, .sub-print-slip th { border: 1px solid #000; padding: 3px 5px; text-align: left; font-size: 9pt; vertical-align: top; }
        .sub-print-slip .no-border td, .sub-print-slip .no-border { border: none; }
        .sub-print-slip .field-label { font-weight: bold; background: #f0f0f0; width: 1%; white-space: nowrap; }
        .sub-print-slip .mockup-box { border: 2px dashed #999; display: flex; align-items: center; justify-content: center; text-align: center; color: #999; font-size: 9pt; overflow: hidden; width:100%; aspect-ratio: 4 / 3; max-height:300px; }
        .sub-print-slip .mockup-box img { max-width: 100%; max-height: 100%; object-fit: contain; }
        .sub-print-slip .roster-table th { background: #e0e0e0; font-weight: bold; text-align: center; }
        .sub-print-slip .roster-table td { text-align: center; }
        .sub-print-slip .section-title { font-weight: bold; font-size: 11pt; margin-top: 4px; margin-bottom: 2px; }
        .sub-print-slip .divider { border-top: 2px solid #000; margin: 1px 0; }
        #subPrintSlip > tbody > tr > td { padding: 1px 3px !important; }
        #subPrintSlip table td, #subPrintSlip table th { padding: 1px 3px !important; font-size: 9pt; }
        #subPrintSlip .section-title { margin-top: 1px; margin-bottom: 1px; font-size: 11pt; }
        #subPrintSlip .field-label { padding: 1px 3px !important; }
    </style>
    <div id="subPrintSlipContent" class="sub-print-slip">
        <h1>CUSTOMER FORM SPECIFICATIONS</h1>
        <div class="divider"></div>
        <table id="subPs_upperInfo"><tr>
            <td style="width:33%;vertical-align:top;" class="no-border">
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">PROJECT:</td><td id="subPs_projectName"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">DESCRIPTION:</td><td id="subPs_description"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">FABRIC:</td><td id="subPs_fabric"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">DESIGNER:</td><td id="subPs_designer"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">QTY:</td><td id="subPs_qty"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">DATE NEEDED:</td><td id="subPs_dateNeeded"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">AGENT:</td><td id="subPs_agent"></td></tr></table>
                <table style="width:100%;"><tr><td class="field-label" style="width:100px;">CUSTOMER:</td><td id="subPs_customer"></td></tr></table>
            </td>
            <td style="width:67%;vertical-align:top;">
                <div style="width:100%;">
                    <table id="subPs_leftPartsCol" style="width:49%;float:left;">
                        <tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>
                    </table>
                    <table id="subPs_rightPartsCol" style="width:49%;float:right;">
                        <tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>
                    </table>
                    <div style="clear:both;"></div>
                </div>
                <div style="display:none;">
                <table id="subPs_specsParts">
                    <tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>
                </table>
                <table id="subPs_specsOthers">
                    <tr><th style="width:100px;">Item</th><th>Details</th></tr>
                </table>
                </div>
            </td>
        </tr></table>
        <div class="divider"></div>
        <table><tr>
            <td style="width:30%;vertical-align:top" class="no-border">
                <div class="section-title">MOCK UP</div>
                <div id="subPs_mockupBox" class="mockup-box" style="margin:0 auto;">
                    <span id="subPs_mockupPlaceholder">MOCK UP HERE</span>
                    <img id="subPs_mockupImg" src="" style="display:none;">
                </div>
            </td>
            <td style="width:70%;vertical-align:top" class="no-border">
                <div class="section-title">NAME LIST</div>
                <table class="roster-table" id="subPs_rosterTable">
                    <thead></thead>
                    <tbody id="subPs_rosterBody"></tbody>
                </table>
            </td>
        </tr></table>
        <div style="margin-top:4px;font-size:9pt;text-align:right;border-top:1px solid #000;padding-top:2px;" id="subPs_note"></div>
    </div>
</div>

<script>
// ======= PRINT ORDER SLIP (CUSTOMER FORM SPECIFICATIONS format) =======
window.sub_printOrderSlip = function() {
    // Helper
    function getVal(id) { var el = document.getElementById(id); return el ? el.value || '' : ''; }
    function formatDateDDMMYYYY(dateStr) {
        if (!dateStr) return '';
        var parts = dateStr.split('-');
        if (parts.length === 3) return parts[2] + '/' + parts[1] + '/' + parts[0];
        return dateStr;
    }
    
    // Header info fields
    document.getElementById('subPs_projectName').textContent = getVal('sub_projectName');
    document.getElementById('subPs_description').textContent = getVal('sub_description');
    
    var fabricEl = document.getElementById('sub_fabricSelect');
    var fabricText = '';
    if (fabricEl) {
        var selOpt = fabricEl.options[fabricEl.selectedIndex];
        if (selOpt && selOpt.value && selOpt.textContent.trim() !== '-- Select Fabric --') {
            fabricText = selOpt.textContent;
        }
    }
    document.getElementById('subPs_fabric').textContent = fabricText;
    document.getElementById('subPs_designer').textContent = getVal('sub_designer');
    document.getElementById('subPs_dateNeeded').textContent = formatDateDDMMYYYY(getVal('sub_dateNeeded'));
    
    // Agent and Customer
    var agentName = '{{ isset($sale) ? ($sale->sales_agent_name ?? 'N/A') : '' }}';
    var customerName = '{{ isset($sale) ? ($sale->customer_name ?? 'N/A') : '' }}';
    // Fallback for kanban
    if (!customerName) {
        customerName = document.getElementById('subAddProductModal').dataset.customerName || '';
    }
    document.getElementById('subPs_agent').textContent = agentName || '';
    document.getElementById('subPs_customer').textContent = customerName || '';
    
    // Total QTY
    var totalQty = 0;
    document.querySelectorAll('.sub-size-qty').forEach(function(inp) { totalQty += parseInt(inp.value) || 0; });
    document.querySelectorAll('#subRosterBody tr.roster-row').forEach(function(row) {
        var qtyInput = row.querySelector('.roster-number');
        totalQty += qtyInput ? (parseInt(qtyInput.value) || 1) : 1;
    });
    document.getElementById('subPs_qty').textContent = totalQty + ' PCS';
    
    // Mock-up image
    var mockupPreview = document.getElementById('subMockupPreview');
    var mockupImg = document.getElementById('subPs_mockupImg');
    var mockupPlaceholder = document.getElementById('subPs_mockupPlaceholder');
    if (mockupPreview && mockupPreview.src && mockupPreview.style.display !== 'none') {
        mockupImg.src = mockupPreview.src;
        mockupImg.style.display = '';
        mockupPlaceholder.style.display = 'none';
    } else {
        mockupImg.style.display = 'none';
        mockupPlaceholder.style.display = '';
    }
    
    // Garment name
    var garmentEl = document.getElementById('sub_garmentSelect');
    var garmentName = garmentEl && garmentEl.selectedIndex > 0 ? garmentEl.options[garmentEl.selectedIndex].textContent : '';
    
    // Parts / Colors table (dynamic — reads whatever spec fields are rendered for current garment type)
    var partsTbody = document.querySelector('#subPs_specsParts tbody');
    if (!partsTbody) partsTbody = document.querySelector('#subPs_specsParts');
    partsTbody.innerHTML = '<tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>';
    partsTbody.innerHTML += '<tr><td>Garment</td><td>' + garmentName + '</td></tr>';
    
    // Collect spec field data — dynamically read ALL rendered spec fields
    document.querySelectorAll('#sub_specsFields select.sub-spec-select').forEach(function(el) {
        var labelEl = el.closest('.d-flex').querySelector('.form-label');
        var label = labelEl ? labelEl.textContent.trim() : el.getAttribute('data-fid') || 'Spec';
        var val = (el.value || '').trim();
        if (val) {
            partsTbody.innerHTML += '<tr><td>' + label + '</td><td>' + val + '</td></tr>';
        }
    });
    // Also read any text input spec fields
    document.querySelectorAll('#sub_specsFields input.sub-spec-input').forEach(function(el) {
        var labelEl = el.closest('.d-flex').querySelector('.form-label');
        var label = labelEl ? labelEl.textContent.trim() : el.getAttribute('data-fid') || 'Spec';
        var val = (el.value || '').trim();
        if (val) {
            partsTbody.innerHTML += '<tr><td>' + label + '</td><td>' + val + '</td></tr>';
        }
    })
    
    // Split parts rows into two columns
    var allPartsTrs = partsTbody.querySelectorAll('tr');
    var dataPartsRows = Array.from(allPartsTrs).slice(1);
    var splitMid = Math.ceil(dataPartsRows.length / 2);
    var splitHeader = '<tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>';
    document.getElementById('subPs_leftPartsCol').innerHTML = splitHeader + dataPartsRows.slice(0, splitMid).map(function(r) { return r.outerHTML; }).join('');
    document.getElementById('subPs_rightPartsCol').innerHTML = splitHeader + dataPartsRows.slice(splitMid).map(function(r) { return r.outerHTML; }).join('');
    
    // Parts Added (from checkboxes)
    var othersTbody = document.querySelector('#subPs_specsOthers tbody');
    if (!othersTbody) othersTbody = document.querySelector('#subPs_specsOthers');
    othersTbody.innerHTML = '<tr><th style="width:100px;">Part</th><th>Color/Details</th></tr>';
    var checkboxes = document.querySelectorAll('#sub_partsContainer .part-checkbox:checked');
    if (checkboxes.length > 0) {
        othersTbody.innerHTML += '<tr><td>Parts Added</td><td>' + Array.from(checkboxes).map(function(cb) {
            var lbl = cb.nextElementSibling;
            return lbl ? lbl.textContent.split(' (+')[0] : '';
        }).filter(Boolean).join(', ') + '</td></tr>';
    }
    
    // Notes
    var notesVal = getVal('sub_notes');
    document.getElementById('subPs_note').textContent = notesVal ? 'Note: ' + notesVal : '';
    
    // Roster table — dynamic columns from Excel import
    var rosterBody = document.getElementById('subPs_rosterBody');
    rosterBody.innerHTML = '';
    var rosterTable = document.getElementById('subPs_rosterTable');
    var rosterRows = document.querySelectorAll('#subRosterBody tr.roster-row');
    if (rosterRows.length > 0) {
        // Read ALL headers from roster
        var headerRow = document.getElementById('subRosterHeader');
        var colHeaders = ['#'];
        if (headerRow) {
            var ths = headerRow.querySelectorAll('th');
            for (var ci = 1; ci < ths.length - 1; ci++) {
                colHeaders.push((ths[ci].textContent || '').trim());
            }
        } else {
            colHeaders = ['#', 'NAME', 'SIZE', 'QTY'];
        }
        // Build dynamic thead
        var thead = rosterTable.querySelector('thead');
        if (!thead) { thead = document.createElement('thead'); rosterTable.insertBefore(thead, rosterBody); }
        var hdrHtml = '<tr>';
        colHeaders.forEach(function(h) { hdrHtml += '<th>' + h + '</th>'; });
        hdrHtml += '</tr>';
        thead.innerHTML = hdrHtml;
        
        // Build data rows
        var idx = 1;
        rosterRows.forEach(function(row) {
            var tds = row.querySelectorAll('td');
            if (tds.length < 2) return;
            var dataCells = [];
            for (var i = 1; i < tds.length - 1; i++) {
                dataCells.push(tds[i]);
            }
            var hasData = dataCells.some(function(td) {
                return (td.textContent || '').trim() !== '';
            });
            if (!hasData) return;
            var rowHtml = '<tr><td>' + (idx++) + '</td>';
            for (var dc = 0; dc < dataCells.length; dc++) {
                var val = (dataCells[dc].textContent || '').trim();
                rowHtml += '<td style="text-align:left;">' + val + '</td>';
            }
            rowHtml += '</tr>';
            rosterBody.innerHTML += rowHtml;
        });
    } else {
        // Fallback: show sizes from by-qty inputs
        var thead = rosterTable.querySelector('thead');
        if (thead) thead.innerHTML = '<tr><th>Size</th><th>Qty</th></tr>';
        document.querySelectorAll('.sub-size-qty').forEach(function(inp) {
            var qty = parseInt(inp.value) || 0;
            if (qty > 0) {
                rosterBody.innerHTML += '<tr><td>' + inp.dataset.size + '</td><td>' + qty + '</td></tr>';
            }
        });
    }
    
    // Show and print
    var slip = document.getElementById('subPrintSlip');
    slip.style.display = 'block';
    window.print();
    slip.style.display = 'none';
};

</script>
