<!-- 
  Fullsublimation Add Product Modal for Show Page
  Same as create page's modal but with quick-mode:
  - Order Details fields auto-filled from sale context, disabled
  - "Add to Order" instead of "Add to Cart"
-->
<style>
    .product-modal .modal-dialog { max-width: 900px; }
    .product-modal .tab-content { min-height: 350px; }
    .product-modal .size-input-group { gap: 0.5rem; }
    .product-modal .size-input-group label { font-size: 0.8rem; margin-bottom: 0.2rem; }
    .product-modal .size-input-group input[type="number"] { text-align: center; }
    .product-modal .roster-row td { vertical-align: middle; padding: 2px 4px; }
    .product-modal .roster-row select { font-size: 0.85rem; }
    #subExcelDropZone { border: 2px dashed #ccc; border-radius: 8px; padding: 20px; text-align: center; cursor: pointer; background: #fafafa; transition: all 0.3s; }
    #subExcelDropZone:hover { border-color: #6c63ff; background: #f0eeff; }
    #subExcelDropZone.has-file { border-color: #28a745; background: #f0fff0; }
    .sub-size-qty { text-align: center; }
    /* Gray out redundant fields */
    .sub-quick-disabled { background: #e9ecef !important; opacity: 0.85; cursor: default !important; }
    .sub-quick-disabled:focus { box-shadow: none !important; }
</style>

<div class="modal fade product-modal" id="subAddProductModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold">
                    <i class="fas fa-box"></i> ➕ Add Fullsublimation Product
                    <span class="badge bg-info ms-2" style="font-size:0.7rem;">To Order #{{ $sale->sales_number }}</span>
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs mb-3" id="subSublimationTab" role="tablist">
                    <li class="nav-item"><button class="nav-link active" id="sub-order-details-tab" data-bs-toggle="tab" data-bs-target="#sub-order-details" type="button" role="tab">Order Details</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-specs-tab" data-bs-toggle="tab" data-bs-target="#sub-specs" type="button" role="tab">Specifications</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-sizes-tab" data-bs-toggle="tab" data-bs-target="#sub-sizes" type="button" role="tab">Sizes</button></li>
                    <li class="nav-item"><button class="nav-link" id="sub-pricing-tab" data-bs-toggle="tab" data-bs-target="#sub-pricing-body" type="button" role="tab">Pricing</button></li>
                </ul>

                <div class="tab-content" id="subSublimationTabContent">
                    <!-- TAB 1: ORDER DETAILS -->
                    <div class="tab-pane fade show active" id="sub-order-details" role="tabpanel">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <label class="form-label">Project Name *</label>
                                        <input type="text" class="form-control sub-quick-disabled" id="sub_projectName" placeholder="e.g. DANNA" required oninput="sub_autoGenerateDescription()">
                                        <div class="form-text small text-success">Auto-filled from existing order</div>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Description *</label>
                                        <input type="text" class="form-control" id="sub_description" placeholder="Auto-generated from selections" readonly style="background:#f0f0f0;cursor:default;">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Fabric *</label>
                                        <select class="form-control" id="sub_fabricSelect" onchange="sub_calculateTotal(); sub_autoGenerateDescription()">
                                            <option value="">-- Select Fabric --</option>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Designer *</label>
                                        <input type="text" class="form-control" id="sub_designer" placeholder="e.g. ALLAN - CONSOL" required>
                                    </div>
                                    <div class="col-md-4">
                                        <label class="form-label">Date Needed *</label>
                                        <input type="date" class="form-control" id="sub_dateNeeded" required>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <label class="form-label">Notes / Special Instructions</label>
                                    <textarea class="form-control" id="sub_notes" rows="2" placeholder="Additional notes..."></textarea>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="card border-primary">
                                    <div class="card-header bg-primary text-white small py-2">
                                        <i class="fas fa-image me-1"></i> Mock-up Design
                                    </div>
                                    <div class="card-body py-2 text-center">
                                        <div id="subMockupPreviewArea" class="mb-2" style="min-height:140px;display:flex;align-items:center;justify-content:center;border:2px dashed #ddd;border-radius:8px;cursor:pointer;background:#fafafa;overflow:hidden;" onclick="document.getElementById('subMockupUpload').click()">
                                            <div id="subMockupPlaceholder">
                                                <i class="fas fa-cloud-upload-alt fa-3x text-muted"></i>
                                                <p class="text-muted small mb-0 mt-1">Click to upload mock-up image</p>
                                            </div>
                                            <img id="subMockupPreview" src="" style="max-height:180px;display:none;max-width:100%;object-fit:contain;">
                                        </div>
                                        <input type="file" id="subMockupUpload" accept="image/*" style="display:none" onchange="sub_previewMockup(event)">
                                        <div id="subMockupFileInfo" class="small" style="display:none;">
                                            <span id="subMockupFileName" class="text-muted"></span>
                                            <button type="button" class="btn btn-sm btn-outline-danger ms-2 py-0 px-1" onclick="sub_removeMockup()"><i class="fas fa-times"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- TAB 2: SPECIFICATIONS -->
                    <div class="tab-pane fade" id="sub-specs" role="tabpanel">
                        <div class="row g-3 mb-3">
                            <div class="col-md-6">
                                <label class="form-label">Garment Type *</label>
                                <select class="form-control" id="sub_garmentSelect" onchange="sub_renderSpecs(); sub_calculateTotal(); sub_autoGenerateDescription()">
                                    <option value="">-- Select Garment --</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Additional Parts</label>
                                <div id="sub_partsContainer" class="border rounded p-2 bg-light" style="max-height:80px;overflow-y:auto;">
                                    <p class="text-muted small mb-0">Select Garment type first...</p>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div id="sub_specsFields">
                            <p class="text-muted small mb-0">Select a garment type to see specifications.</p>
                        </div>
                    </div>

                    <!-- TAB 3: SIZES -->
                    <div class="tab-pane fade" id="sub-sizes" role="tabpanel">
                        <div class="btn-group btn-group-sm mb-3 w-100" role="group">
                            <input type="radio" class="btn-check" name="subSizeMode" id="subSizeModeByQty" value="by-qty" checked onchange="sub_toggleSizeMode()">
                            <label class="btn btn-outline-primary" for="subSizeModeByQty"><i class="fas fa-list-ol me-1"></i>By Size</label>
                            <input type="radio" class="btn-check" name="subSizeMode" id="subSizeModeRoster" value="roster" onchange="sub_toggleSizeMode()">
                            <label class="btn btn-outline-primary" for="subSizeModeRoster"><i class="fas fa-users me-1"></i>Per Person (Names)</label>
                        </div>

                        <!-- MODE 1: BY SIZE -->
                        <div id="subSizeByQty">
                            <div class="alert alert-info py-2 small">
                                <i class="fas fa-info-circle me-1"></i> Enter quantity per size. Total auto-calculated.
                            </div>
                            <div class="row g-2">
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">XS</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="XS" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Small</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="SMALL" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Medium</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="MEDIUM" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">Large</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="LARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">2XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="2XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">3XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="3XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">4XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="4XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">5XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="5XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">6XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="6XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">7XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="7XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                                <div class="col-md-4 col-6">
                                    <label class="form-label small">8XLARGE</label>
                                    <input type="number" class="form-control form-control-sm sub-size-qty" data-size="8XLARGE" min="0" value="0" oninput="sub_calculateTotal()">
                                </div>
                            </div>
                        </div>

                        <!-- MODE 2: PER PERSON -->
                        <div id="subSizeRoster" style="display:none;">
                            <div class="alert alert-success py-2 small">
                                <i class="fas fa-users me-1"></i> Add each person's name and assigned size.
                            </div>
                            <div class="row g-2 mb-2 align-items-end">
                                <div class="col-2">
                                    <label class="form-label small mb-0">#</label>
                                    <input type="text" class="form-control form-control-sm" id="subRosterNewNumber" placeholder="No.">
                                </div>
                                <div class="col-4">
                                    <label class="form-label small mb-0">Name *</label>
                                    <input type="text" class="form-control form-control-sm" id="subRosterNewName" placeholder="Person's name">
                                </div>
                                <div class="col-3">
                                    <label class="form-label small mb-0">Size *</label>
                                    <select class="form-control form-control-sm" id="subRosterNewSize">
                                        <option value="">--</option>
                                        <option value="XS">XS</option>
                                        <option value="S">S</option>
                                        <option value="M">M</option>
                                        <option value="L">L</option>
                                        <option value="XL">XL</option>
                                        <option value="2XL">2XL</option>
                                        <option value="3XL">3XL</option>
                                        <option value="4XL">4XL</option>
                                        <option value="5XL">5XL</option>
                                        <option value="6XL">6XL</option>
                                        <option value="7XL">7XL</option>
                                        <option value="8XL">8XL</option>
                                    </select>
                                </div>
                                <div class="col-3">
                                    <label class="form-label small mb-0">&nbsp;</label>
                                    <button type="button" class="btn btn-success btn-sm w-100" onclick="sub_addRosterRow()">
                                        <i class="fas fa-plus"></i> Add
                                    </button>
                                </div>
                            </div>

                            <div class="mb-2">
                                <div class="d-flex gap-2 flex-wrap">
                                    <button type="button" class="btn btn-outline-secondary btn-sm" onclick="sub_toggleBulkPaste()">
                                        <i class="fas fa-paste me-1"></i>Bulk Paste List
                                    </button>
                                    <button type="button" class="btn btn-outline-primary btn-sm" onclick="document.getElementById('subExcelInput').click()">
                                        <i class="fas fa-file-excel me-1"></i>Upload Excel
                                    </button>
                                    <input type="file" id="subExcelInput" accept=".xlsx,.xls,.csv" style="display:none" onchange="sub_uploadExcel(event)">
                                </div>
                                <div id="subBulkPasteArea" style="display:none;" class="mt-2">
                                    <label class="form-label small">Paste one per line: <code>Name,Size</code> or <code>Number,Name,Size</code></label>
                                    <textarea class="form-control form-control-sm" id="subBulkPasteInput" rows="4" placeholder="e.g.&#10;MON,XL&#10;KOKO,L&#10;MANEX,XL&#10;JUN,L&#10;GERBIE,M"></textarea>
                                    <button type="button" class="btn btn-info btn-sm mt-1" onclick="sub_bulkPaste()">
                                        <i class="fas fa-upload me-1"></i>Import List
                                    </button>
                                </div>
                            </div>

                            <div class="table-responsive" style="max-height:300px;overflow-y:auto;">
                                <table class="table table-sm table-bordered mb-0" id="subRosterTable">
                                    <thead class="table-light">
                                        <tr>
                                            <th style="width:50px">#</th>
                                            <th>Name</th>
                                            <th style="width:80px">Size</th>
                                            <th style="width:40px">Qty</th>
                                            <th style="width:40px"></th>
                                        </tr>
                                    </thead>
                                    <tbody id="subRosterBody">
                                        <tr id="subRosterEmpty">
                                            <td colspan="5" class="text-center text-muted small py-3">
                                                <i class="fas fa-user-plus me-1"></i> Add names above to build your roster.
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="mt-1 text-end">
                                <small class="text-muted"><span id="subRosterCount">0</span> people</small>
                            </div>
                        </div>
                    </div>

                    <!-- TAB 4: PRICING -->
                    <div class="tab-pane fade" id="sub-pricing-body" role="tabpanel">
                        <div class="card border-success mt-3">
                            <div class="card-header bg-success text-white small py-2">
                                <i class="fas fa-file-invoice me-1"></i> Full Price Breakdown
                            </div>
                            <div class="card-body py-2">
                                <div class="d-flex justify-content-between small">
                                    <span id="subPricing_garmentLabel">Garment:</span>
                                    <strong><span id="subPricing_garmentPrice">₱0.00</span></strong>
                                </div>
                                <div class="d-flex justify-content-between small">
                                    <span id="subPricing_fabricLabel">Fabric:</span>
                                    <strong><span id="subPricing_fabricPrice">₱0.00</span></strong>
                                </div>
                                <div id="subPricing_partsBreakdown"></div>
                                <div id="subPricing_sizeBreakdown"></div>
                                <hr class="my-1">
                                <div class="d-flex justify-content-between">
                                    <span class="fw-bold">Per Unit (base):</span>
                                    <strong class="fs-6"><span id="subPricing_unitPrice">₱0.00</span></strong>
                                </div>
                                <div class="d-flex justify-content-between small">
                                    <span>Total Qty (from Sizes tab):</span>
                                    <strong><span id="subPricing_totalQty">0</span></strong>
                                </div>
                                <hr class="my-1">
                                <div class="d-flex justify-content-between fw-bold fs-5" style="color:#198754;">
                                    <span>TOTAL:</span>
                                    <span id="subPricing_grandTotal">₱0.00</span>
                                </div>
                                <div id="subSpecialPriceIndicator" class="alert alert-warning py-1 small mb-0 mt-2" style="display:none;">
                                    <i class="fas fa-tag me-1"></i> <strong>Special Price:</strong> <span id="subSpecialPriceDisplay">₱0.00</span>/piece
                                </div>
                            </div>
                        </div>

                        <div class="mt-3 p-2 bg-light rounded" id="subSpecialPriceSection" style="display:none;">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="fw-bold small">💵 SPECIAL PRICE ACTIVE</span>
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="sub_clearSpecialPrice()">✕ Clear</button>
                            </div>
                            <div class="mb-2">
                                <label class="small text-muted">Set Price Per Piece:</label>
                                <div class="input-group input-group-sm">
                                    <span class="input-group-text">₱</span>
                                    <input type="number" class="form-control" id="subSpecialPrintTotal" min="0" step="0.01" placeholder="0.00/piece" oninput="sub_onSpecialPriceChange()">
                                </div>
                            </div>
                            <div class="mb-2">
                                <label class="small text-muted">Reason *</label>
                                <input type="text" class="form-control form-control-sm" id="subSpecialPriceReason" placeholder="Why special price?" required>
                            </div>
                        </div>

                        <button type="button" class="btn btn-outline-warning btn-sm w-100 mt-2" id="subSpecialPriceBtn" onclick="sub_toggleSpecialPrice()">
                            💰 Special Price
                        </button>

                        <button type="button" class="btn btn-success w-100 mt-2" id="subAddItemBtn" onclick="sub_addItemToOrder()">
                            <i class="fas fa-check-circle me-2"></i> Add to Order
                        </button>
                        <button type="button" class="btn btn-outline-info w-100 mt-2" id="subPrintOrderSlip" onclick="sub_printOrderSlip()">
                            <i class="fas fa-print me-2"></i> Print Order Slip
                        </button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!-- Column Mapping Modal -->
<div class="modal fade" id="subColumnMapModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h6 class="modal-title"><i class="fas fa-columns me-1"></i>Map Columns</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body py-2 small">
                <p class="mb-2 text-muted">Match your Excel columns to roster fields:</p>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Name</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_name"><option value="">-- skip --</option></select>
                </div>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Number</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_number"><option value="">-- skip --</option></select>
                </div>
                <div class="mb-2">
                    <label class="form-label mb-0">→ <strong>Size</strong> column</label>
                    <select class="form-select form-select-sm" id="subMapCol_size"><option value="">-- skip --</option></select>
                </div>
                <small class="text-muted" id="subMapPreview">Loading preview...</small>
            </div>
            <div class="modal-footer py-1">
                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-sm btn-success" onclick="sub_applyMapping()">
                    <i class="fas fa-check me-1"></i>Import
                </button>
            </div>
        </div>
    </div>
</div>

<script>
// Load XLSX library if not available
if (typeof XLSX === 'undefined') {
    var script = document.createElement('script');
    script.src = 'https://cdn.sheetjs.com/xlsx-0.20.2/package/dist/xlsx.full.min.js';
    script.onload = function() { console.log('XLSX loaded for Add Product modal'); };
    document.head.appendChild(script);
}

// ======= DATA =======
window.sub_sizesData = {};
window.sub_hasSpecialPrice = false;
window.sub_excelData = null;
window.sub_excelHeaders = null;

// ======= OPEN =======
window.openSubAddProductModal = function() {
    // Auto-fill Order Details from sale context
    <?php
        $__saleServices = is_string($sale->services) ? json_decode($sale->services, true) : (array)$sale->services;
        $__firstItemName = '';
        if (is_array($__saleServices) && count($__saleServices) > 0) {
            $__first = $__saleServices[0];
            $__firstItemName = $__first['name'] ?? $__first['projectName'] ?? $__first['project_name'] ?? '';
        }
    ?>
    var projectName = document.getElementById('sub_projectName');
    if (<?php echo json_encode($__firstItemName); ?>) {
        projectName.value = <?php echo json_encode($__firstItemName); ?>;
    }
    
    // Auto-fill date needed with a reasonable default (2 weeks from now)
    var d = new Date();
    d.setDate(d.getDate() + 14);
    document.getElementById('sub_dateNeeded').value = d.toISOString().split('T')[0];

    // Disable project name (redundant on existing order)
    projectName.disabled = true;
    projectName.readOnly = true;
    projectName.classList.add('sub-quick-disabled');
    
    // Reset everything else
    document.getElementById('sub_description').value = '';
    document.getElementById('sub_designer').value = '';
    document.getElementById('sub_notes').value = '';
    
    // Reset parts
    var partsCont = document.getElementById('sub_partsContainer');
    partsCont.innerHTML = '<p class="text-muted small mb-0">Select Garment type first...</p>';
    
    // Reset sizes
    document.querySelectorAll('.sub-size-qty').forEach(function(el) { el.value = '0'; });
    
    // Reset roster
    var rosterBody = document.getElementById('subRosterBody');
    var rows = rosterBody.querySelectorAll('tr.roster-row');
    rows.forEach(function(r) { r.remove(); });
    var empty = document.getElementById('subRosterEmpty');
    if (empty) empty.style.display = '';
    document.getElementById('subRosterCount').textContent = '0';
    
    // Reset size mode
    document.getElementById('subSizeModeByQty').checked = true;
    sub_toggleSizeMode();
    
    // Reset mockup
    sub_removeMockup();
    
    // Reset special price
    var spSec = document.getElementById('subSpecialPriceSection');
    var spBtn = document.getElementById('subSpecialPriceBtn');
    if (spSec) spSec.style.display = 'none';
    if (spBtn) { spBtn.textContent = '💰 Special Price'; spBtn.classList.remove('btn-warning'); spBtn.classList.add('btn-outline-warning'); }
    document.getElementById('subSpecialPrintTotal').value = '';
    document.getElementById('subSpecialPriceReason').value = '';
    window.sub_hasSpecialPrice = false;
    
    // Reset garment/fabric selects
    var garmentSel = document.getElementById('sub_garmentSelect');
    var fabricSel = document.getElementById('sub_fabricSelect');
    if (garmentSel) garmentSel.innerHTML = '<option value="">Loading...</option>';
    if (fabricSel) fabricSel.innerHTML = '<option value="">Loading...</option>';
    document.getElementById('sub_specsFields').innerHTML = '<p class="text-muted small mb-0">Select a garment type to see specifications.</p>';
    
    // Fetch sublimation prices
    fetch('/api/sublimation-prices')
        .then(function(r) { return r.json(); })
        .then(function(data) {
            window.sub_sizesData = {};
            if (data.sizes && data.sizes.length) {
                data.sizes.forEach(function(item) {
                    window.sub_sizesData[item.name.toUpperCase()] = parseFloat(item.price) || 0;
                });
            }
            // Populate garment select
            if (garmentSel) {
                garmentSel.innerHTML = '<option value="">-- Select Garment --</option>';
                data.garments.forEach(function(item) {
                    var opt = document.createElement('option');
                    opt.value = item.id || item.name;
                    opt.textContent = item.name;
                    opt.dataset.price = item.price || 0;
                    garmentSel.appendChild(opt);
                });
            }
            // Populate fabric select
            if (fabricSel) {
                fabricSel.innerHTML = '<option value="">-- Select Fabric --</option>';
                data.fabrics.forEach(function(item) {
                    var opt = document.createElement('option');
                    opt.value = item.id || item.name;
                    opt.textContent = item.name;
                    opt.dataset.price = item.price || 0;
                    fabricSel.appendChild(opt);
                });
            }
            sub_calculateTotal();
        })
        .catch(function() {
            if (garmentSel) garmentSel.innerHTML = '<option value="">Error loading</option>';
            if (fabricSel) fabricSel.innerHTML = '<option value="">Error loading</option>';
        });
    
    // Switch to first tab
    var firstTab = document.querySelector('#subSublimationTab .nav-link');
    if (firstTab && typeof bootstrap !== 'undefined') {
        var tab = new bootstrap.Tab(firstTab);
        tab.show();
    }
    
    // Show modal
    var modal = new bootstrap.Modal(document.getElementById('subAddProductModal'));
    modal.show();
};

// ======= MOCKUP =======
window.sub_previewMockup = function(event) {
    var file = event.target.files[0];
    if (!file) return;
    var reader = new FileReader();
    reader.onload = function(e) {
        document.getElementById('subMockupPreview').src = e.target.result;
        document.getElementById('subMockupPreview').style.display = 'block';
        document.getElementById('subMockupPlaceholder').style.display = 'none';
        document.getElementById('subMockupFileInfo').style.display = 'block';
        document.getElementById('subMockupFileName').textContent = file.name;
    };
    reader.readAsDataURL(file);
};

window.sub_removeMockup = function() {
    document.getElementById('subMockupPreview').src = '';
    document.getElementById('subMockupPreview').style.display = 'none';
    document.getElementById('subMockupPlaceholder').style.display = '';
    document.getElementById('subMockupFileInfo').style.display = 'none';
    document.getElementById('subMockupUpload').value = '';
};

// ======= DESCRIPTION =======
window.sub_autoGenerateDescription = function() {
    var garment = document.getElementById('sub_garmentSelect');
    var fabric = document.getElementById('sub_fabricSelect');
    var parts = [];
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        parts.push(cb.value);
    });
    var garmentText = garment.options[garment.selectedIndex] ? garment.options[garment.selectedIndex].text : '';
    var fabricText = fabric.options[fabric.selectedIndex] ? fabric.options[fabric.selectedIndex].text : '';
    var desc = '';
    if (garmentText) desc += garmentText;
    if (fabricText) desc += (desc ? ' - ' : '') + fabricText;
    if (parts.length) desc += (desc ? ' | ' : '') + parts.join('+');
    document.getElementById('sub_description').value = desc;
};

// ======= SPECS RENDER =======
window.sub_renderSpecs = function() {
    var select = document.getElementById('sub_garmentSelect');
    var container = document.getElementById('sub_specsFields');
    var partsCont = document.getElementById('sub_partsContainer');
    var garmentId = select.value;
    
    if (!garmentId) {
        container.innerHTML = '<p class="text-muted small mb-0">Select a garment type to see specifications.</p>';
        partsCont.innerHTML = '<p class="text-muted small mb-0">Select Garment type first...</p>';
        return;
    }
    
    var selectedOpt = select.options[select.selectedIndex];
    container.innerHTML = '<p class="text-muted small"><i class="fas fa-spinner fa-spin me-1"></i>Loading specifications...</p>';
    partsCont.innerHTML = '<p class="text-muted small"><i class="fas fa-spinner fa-spin me-1"></i>Loading parts...</p>';
    
    fetch('/api/sublimation-prices')
        .then(function(r) { return r.json(); })
        .then(function(data) {
            // Garment specs
            var garment = data.garments.find(function(g) { return (g.id == garmentId || g.name == garmentId); });
            if (garment && garment.specifications) {
                var html = '<div class="row g-2">';
                Object.keys(garment.specifications).forEach(function(key) {
                    var val = garment.specifications[key];
                    html += '<div class="col-md-6"><div class="border p-2 rounded bg-light"><strong class="small">' + key + ':</strong> <span class="small">' + val + '</span></div></div>';
                });
                html += '</div>';
                container.innerHTML = html;
            } else {
                container.innerHTML = '<p class="text-muted small mb-0">No specifications available for this garment.</p>';
            }
            
            // Parts (addons)
            if (garment && garment.addons && garment.addons.length) {
                var partsHtml = '';
                garment.addons.forEach(function(addon, idx) {
                    var aName = addon.name || addon.addon_name || '';
                    var aPrice = parseFloat(addon.price || addon.addon_price || 0);
                    partsHtml += '<div class="form-check form-check-inline">';
                    partsHtml += '<input class="form-check-input part-checkbox" type="checkbox" id="sub_part_' + idx + '" value="' + aName + '" data-price="' + aPrice + '" onchange="sub_calculateTotal(); sub_autoGenerateDescription()">';
                    partsHtml += '<label class="form-check-label small" for="sub_part_' + idx + '">' + aName + ' (₱' + aPrice.toFixed(2) + ')</label>';
                    partsHtml += '</div>';
                });
                partsCont.innerHTML = partsHtml;
            } else {
                partsCont.innerHTML = '<p class="text-muted small mb-0">No additional parts available.</p>';
            }
        })
        .catch(function() {
            container.innerHTML = '<p class="text-muted small mb-0">Error loading specifications.</p>';
        });
};

// ======= PRICE CALC =======
window.sub_calculateTotal = function() {
    var garmentSelect = document.getElementById('sub_garmentSelect');
    var fabricSelect = document.getElementById('sub_fabricSelect');
    var sizeInputs = document.querySelectorAll('.sub-size-qty');
    var rosterRows = document.querySelectorAll('#subRosterBody tr.roster-row');
    
    var garmentPrice = 0, fabricPrice = 0, partsPrice = 0, sizeAddon = 0;
    
    // Garment price
    if (garmentSelect.selectedIndex > 0) {
        garmentPrice = parseFloat(garmentSelect.options[garmentSelect.selectedIndex].dataset.price) || 0;
    }
    
    // Fabric price
    if (fabricSelect.selectedIndex > 0) {
        fabricPrice = parseFloat(fabricSelect.options[fabricSelect.selectedIndex].dataset.price) || 0;
    }
    
    // Parts
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        partsPrice += parseFloat(cb.dataset.price) || 0;
    });
    
    // Sizes - count total qty and get size addons
    var totalQty = 0;
    var sizeBreakdownHtml = '';
    
    // Check which mode is active
    var isRoster = document.getElementById('subSizeModeRoster') && document.getElementById('subSizeModeRoster').checked;
    
    if (isRoster) {
        // Count roster rows
        rosterRows.forEach(function(row) {
            var qtyCell = row.querySelector('td:nth-child(4)');
            var qty = parseInt(qtyCell ? qtyCell.textContent : 1) || 1;
            totalQty += qty;
        });
    } else {
        sizeInputs.forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                var size = input.dataset.size;
                var sizePrice = window.sub_sizesData[size] || 0;
                sizeAddon += sizePrice * val;
                totalQty += val;
            }
        });
        
        // Show size breakdown
        var hasSizeDiff = false;
        sizeInputs.forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                var size = input.dataset.size;
                var sizePrice = window.sub_sizesData[size] || 0;
                if (sizePrice > 0) {
                    hasSizeDiff = true;
                    sizeBreakdownHtml += '<div class="d-flex justify-content-between small text-muted"><span>' + size + ' x' + val + '</span><span>+₱' + (sizePrice * val).toFixed(2) + '</span></div>';
                }
            }
        });
        if (hasSizeDiff) {
            sizeBreakdownHtml = '<hr class="my-1"><div class="small fw-bold text-muted">Size Add-ons:</div>' + sizeBreakdownHtml;
        }
    }
    
    var baseUnit = garmentPrice + fabricPrice + partsPrice;
    var maxSizeAddon = 0;
    if (!isRoster) {
        sizeInputs.forEach(function(input) {
            var size = input.dataset.size;
            var sizePrice = window.sub_sizesData[size] || 0;
            if (sizePrice > maxSizeAddon) maxSizeAddon = sizePrice;
        });
    }
    
    var unitPrice = baseUnit + maxSizeAddon;
    if (window.sub_hasSpecialPrice) {
        var spVal = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
        if (spVal > 0) unitPrice = spVal;
    }
    
    var grandTotal = unitPrice * totalQty;
    
    // Update UI
    document.getElementById('subPricing_garmentPrice').textContent = '₱' + garmentPrice.toFixed(2);
    document.getElementById('subPricing_fabricPrice').textContent = '₱' + fabricPrice.toFixed(2);
    
    var partsHtml = '';
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        var label = cb.parentElement.querySelector('label');
        var price = parseFloat(cb.dataset.price) || 0;
        partsHtml += '<div class="d-flex justify-content-between small"><span>' + label.textContent + '</span><strong>+₱' + price.toFixed(2) + '</strong></div>';
    });
    if (partsHtml) {
        partsHtml = '<div class="d-flex justify-content-between small"><span>Parts:</span></div>' + partsHtml;
    }
    document.getElementById('subPricing_partsBreakdown').innerHTML = partsHtml;
    document.getElementById('subPricing_sizeBreakdown').innerHTML = sizeBreakdownHtml;
    document.getElementById('subPricing_unitPrice').textContent = '₱' + unitPrice.toFixed(2);
    document.getElementById('subPricing_totalQty').textContent = totalQty;
    document.getElementById('subPricing_grandTotal').textContent = '₱' + grandTotal.toFixed(2);
    
    // Update special price display
    if (window.sub_hasSpecialPrice) {
        document.getElementById('subSpecialPriceDisplay').textContent = '₱' + unitPrice.toFixed(2);
    }
};

// ======= SPECIAL PRICE =======
window.sub_toggleSpecialPrice = function() {
    var section = document.getElementById('subSpecialPriceSection');
    var btn = document.getElementById('subSpecialPriceBtn');
    if (section.style.display === 'none') {
        section.style.display = 'block';
        btn.textContent = '✕ Cancel Special Price';
        btn.classList.remove('btn-outline-warning');
        btn.classList.add('btn-warning');
    } else {
        sub_clearSpecialPrice();
    }
};

window.sub_clearSpecialPrice = function() {
    document.getElementById('subSpecialPriceSection').style.display = 'none';
    document.getElementById('subSpecialPrintTotal').value = '';
    document.getElementById('subSpecialPriceReason').value = '';
    document.getElementById('subSpecialPriceIndicator').style.display = 'none';
    var btn = document.getElementById('subSpecialPriceBtn');
    btn.textContent = '💰 Special Price';
    btn.classList.remove('btn-warning');
    btn.classList.add('btn-outline-warning');
    window.sub_hasSpecialPrice = false;
    sub_calculateTotal();
};

window.sub_onSpecialPriceChange = function() {
    var val = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
    if (val > 0) {
        window.sub_hasSpecialPrice = true;
        document.getElementById('subSpecialPriceIndicator').style.display = '';
        sub_calculateTotal();
    }
};

// ======= SIZE MODE =======
window.sub_toggleSizeMode = function() {
    var isRoster = document.getElementById('subSizeModeRoster').checked;
    document.getElementById('subSizeByQty').style.display = isRoster ? 'none' : '';
    document.getElementById('subSizeRoster').style.display = isRoster ? '' : 'none';
    sub_calculateTotal();
};

// ======= ROSTER =======
window.sub_addRosterRow = function() {
    var numberEl = document.getElementById('subRosterNewNumber');
    var nameEl = document.getElementById('subRosterNewName');
    var sizeEl = document.getElementById('subRosterNewSize');
    var name = nameEl.value.trim();
    var size = sizeEl.value;
    
    if (!name || !size) { alert('Please enter Name and Size.'); return; }
    
    var emptyRow = document.getElementById('subRosterEmpty');
    if (emptyRow) emptyRow.style.display = 'none';
    
    var tbody = document.getElementById('subRosterBody');
    var count = tbody.querySelectorAll('tr.roster-row').length + 1;
    var tr = document.createElement('tr');
    tr.className = 'roster-row';
    tr.innerHTML = '<td>' + count + '</td>' +
        '<td>' + name + '<input type="hidden" class="roster-name" value="' + name.replace(/"/g, '&quot;') + '"></td>' +
        '<td>' + size + '<input type="hidden" class="roster-size" value="' + size + '"></td>' +
        '<td>1</td>' +
        '<td><button type="button" class="btn btn-sm btn-outline-danger py-0 px-1" onclick="sub_removeRosterRow(this)"><i class="fas fa-times"></i></button></td>';
    tbody.appendChild(tr);
    
    nameEl.value = '';
    sizeEl.selectedIndex = 0;
    sub_updateRosterCount();
    sub_calculateTotal();
};

window.sub_removeRosterRow = function(btn) {
    var tr = btn.closest('tr');
    tr.remove();
    // Renumber
    var tbody = document.getElementById('subRosterBody');
    tbody.querySelectorAll('tr.roster-row').forEach(function(row, idx) {
        row.cells[0].textContent = idx + 1;
    });
    if (tbody.querySelectorAll('tr.roster-row').length === 0) {
        document.getElementById('subRosterEmpty').style.display = '';
    }
    sub_updateRosterCount();
    sub_calculateTotal();
};

window.sub_updateRosterCount = function() {
    var count = document.querySelectorAll('#subRosterBody tr.roster-row').length;
    document.getElementById('subRosterCount').textContent = count;
};

window.sub_toggleBulkPaste = function() {
    var area = document.getElementById('subBulkPasteArea');
    area.style.display = area.style.display === 'none' ? 'block' : 'none';
};

window.sub_bulkPaste = function() {
    var text = document.getElementById('subBulkPasteInput').value.trim();
    if (!text) { alert('Please paste a list first.'); return; }
    var lines = text.split('\n').filter(function(l) { return l.trim(); });
    
    lines.forEach(function(line) {
        var parts = line.split(',').map(function(p) { return p.trim(); });
        var name, size;
        if (parts.length === 2) {
            name = parts[0]; size = parts[1];
        } else if (parts.length >= 3) {
            name = parts[1]; size = parts[2];
        } else return;
        
        document.getElementById('subRosterNewName').value = name;
        var sizeSelect = document.getElementById('subRosterNewSize');
        for (var i = 0; i < sizeSelect.options.length; i++) {
            if (sizeSelect.options[i].value.toUpperCase() === size.toUpperCase()) {
                sizeSelect.selectedIndex = i;
                break;
            }
        }
        sub_addRosterRow();
    });
    document.getElementById('subBulkPasteInput').value = '';
    document.getElementById('subBulkPasteArea').style.display = 'none';
};

// ======= EXCEL =======
window.sub_uploadExcel = function(event) {
    var file = event.target.files[0];
    if (!file) return;
    
    var reader = new FileReader();
    reader.onload = function(e) {
        try {
            var data = new Uint8Array(e.target.result);
            var workbook = XLSX.read(data, {type: 'array'});
            var firstSheet = workbook.Sheets[workbook.SheetNames[0]];
            var jsonData = XLSX.utils.sheet_to_json(firstSheet, {header: 1});
            
            if (jsonData.length < 2) {
                alert('Excel file must have at least a header row and one data row.');
                return;
            }
            
            var headers = jsonData[0];
            var rows = jsonData.slice(1);
            
            // Auto-detect columns
            var nameCol = -1, numberCol = -1, sizeCol = -1;
            var namePatterns = ['name', 'player', 'person', 'employee', 'staff', 'first', 'last', 'full'];
            var numberPatterns = ['number', 'no', '#', 'jersey', 'id', 'code'];
            var sizePatterns = ['size', 'sizes', 'shirt', 'uniform'];
            
            headers.forEach(function(h, idx) {
                var hl = (h + '').toLowerCase().trim();
                namePatterns.forEach(function(p) { if (hl.includes(p)) nameCol = idx; });
                numberPatterns.forEach(function(p) { if (hl.includes(p)) numberCol = idx; });
                sizePatterns.forEach(function(p) { if (hl.includes(p)) sizeCol = idx; });
            });
            
            if (nameCol === -1 && sizeCol === -1) {
                // Show column mapping modal
                var nameSel = document.getElementById('subMapCol_name');
                var numberSel = document.getElementById('subMapCol_number');
                var sizeSel = document.getElementById('subMapCol_size');
                nameSel.innerHTML = '<option value="">-- skip --</option>';
                numberSel.innerHTML = '<option value="">-- skip --</option>';
                sizeSel.innerHTML = '<option value="">-- skip --</option>';
                headers.forEach(function(h, idx) {
                    var nameOpt = document.createElement('option');
                    nameOpt.value = idx;
                    nameOpt.textContent = h + ' (col ' + (idx+1) + ')';
                    nameSel.appendChild(nameOpt);
                    var optClone1 = nameOpt.cloneNode(true);
                    numberSel.appendChild(optClone1);
                    var optClone2 = nameOpt.cloneNode(true);
                    sizeSel.appendChild(optClone2);
                });
                window.sub_excelData = rows;
                window.sub_excelHeaders = headers;
                document.getElementById('subMapPreview').textContent = rows.length + ' rows loaded. Please map columns.';
                new bootstrap.Modal(document.getElementById('subColumnMapModal')).show();
                return;
            }
            
            var sizeMap = {xs:'XS',s:'S',m:'M',l:'L',xl:'XL','2xl':'2XL','3xl':'3XL','4xl':'4XL','5xl':'5XL','6xl':'6XL','7xl':'7XL','8xl':'8XL',sm:'SMALL',md:'MEDIUM',lg:'LARGE'};
            rows.forEach(function(row) {
                var name = nameCol >= 0 ? (row[nameCol] || '') + '' : '';
                var size = sizeCol >= 0 ? (row[sizeCol] || '') + '' : '';
                if (!name || !size) return;
                
                size = size.trim().toLowerCase();
                size = sizeMap[size] || size.toUpperCase();
                
                document.getElementById('subRosterNewName').value = name.trim();
                var sizeSelect = document.getElementById('subRosterNewSize');
                for (var i = 0; i < sizeSelect.options.length; i++) {
                    if (sizeSelect.options[i].value === size) {
                        sizeSelect.selectedIndex = i;
                        break;
                    }
                }
                sub_addRosterRow();
            });
        } catch(err) {
            alert('Error reading Excel file: ' + err.message);
        }
    };
    reader.readAsArrayBuffer(file);
};

window.sub_applyMapping = function() {
    var nameCol = parseInt(document.getElementById('subMapCol_name').value);
    var numberCol = parseInt(document.getElementById('subMapCol_number').value);
    var sizeCol = parseInt(document.getElementById('subMapCol_size').value);
    var rows = window.sub_excelData;
    var headers = window.sub_excelHeaders;
    var sizeMap = {xs:'XS',s:'S',m:'M',l:'L',xl:'XL','2xl':'2XL','3xl':'3XL','4xl':'4XL','5xl':'5XL','6xl':'6XL','7xl':'7XL','8xl':'8XL',sm:'SMALL',md:'MEDIUM',lg:'LARGE'};
    
    if (isNaN(sizeCol) && isNaN(nameCol)) {
        alert('Please map at least Size column or Name column.');
        return;
    }
    
    rows.forEach(function(row) {
        var name = !isNaN(nameCol) && nameCol >= 0 ? (row[nameCol] || '') + '' : '';
        var size = !isNaN(sizeCol) && sizeCol >= 0 ? (row[sizeCol] || '') + '' : '';
        if (!name || !size) return;
        
        size = size.trim().toLowerCase();
        size = sizeMap[size] || size.toUpperCase();
        
        document.getElementById('subRosterNewName').value = name.trim();
        var sizeSelect = document.getElementById('subRosterNewSize');
        for (var i = 0; i < sizeSelect.options.length; i++) {
            if (sizeSelect.options[i].value === size) {
                sizeSelect.selectedIndex = i;
                break;
            }
        }
        sub_addRosterRow();
    });
    
    bootstrap.Modal.getInstance(document.getElementById('subColumnMapModal')).hide();
};

// ======= ADD TO ORDER =======
window.sub_addItemToOrder = function() {
    var projectName = document.getElementById('sub_projectName').value.trim();
    var designer = document.getElementById('sub_designer').value.trim();
    var dateNeeded = document.getElementById('sub_dateNeeded').value;
    var garment = document.getElementById('sub_garmentSelect');
    var fabric = document.getElementById('sub_fabricSelect');
    
    if (!projectName) { alert('Please enter Project Name.'); return; }
    if (!designer) { alert('Please enter Designer name.'); return; }
    if (!dateNeeded) { alert('Please select Date Needed.'); return; }
    if (garment.selectedIndex <= 0) { alert('Please select a Garment Type.'); return; }
    
    // Get sizes
    var sizes = [];
    var isRoster = document.getElementById('subSizeModeRoster').checked;
    
    if (isRoster) {
        document.querySelectorAll('#subRosterBody tr.roster-row').forEach(function(row) {
            var name = row.querySelector('.roster-name');
            var size = row.querySelector('.roster-size');
            if (name && size) {
                sizes.push({name: name.value, size: size.value, qty: 1});
            }
        });
    } else {
        document.querySelectorAll('.sub-size-qty').forEach(function(input) {
            var val = parseInt(input.value) || 0;
            if (val > 0) {
                sizes.push({size: input.dataset.size, qty: val});
            }
        });
    }
    
    if (sizes.length === 0) { alert('Please enter at least one size/quantity.'); return; }
    
    // Get specs from fields
    var specs = {};
    document.querySelectorAll('#sub_specsFields input, #sub_specsFields select').forEach(function(el) {
        var label = el.closest('.col-md-6');
        if (label) {
            var lbl = label.querySelector('strong') || label.querySelector('.form-label');
            if (lbl) specs[lbl.textContent.replace(':', '').trim()] = el.value;
        }
    });
    
    // Get parts
    var parts = [];
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        parts.push({name: cb.value, price: parseFloat(cb.dataset.price) || 0});
    });
    
    var garmentName = garment.options[garment.selectedIndex].textContent;
    var fabricName = fabric.selectedIndex > 0 ? fabric.options[fabric.selectedIndex].textContent : '';
    
    // Unit price
    var unitPrice = parseFloat(document.getElementById('subPricing_unitPrice').textContent.replace('₱', '').replace(',', '')) || 0;
    var totalQty = parseInt(document.getElementById('subPricing_totalQty').textContent) || 0;
    var grandTotal = parseFloat(document.getElementById('subPricing_grandTotal').textContent.replace('₱', '').replace(',', '')) || 0;
    
    // Mockup (convert to base64 if uploaded)
    var mockupData = '';
    var mockupImg = document.getElementById('subMockupPreview');
    if (mockupImg.style.display !== 'none' && mockupImg.src) {
        mockupData = mockupImg.src;
    }
    
    // Build item data
    var item = {
        name: projectName,
        productType: 'fullsublimation',
        department: '{{ $sale->department_code ?? $sale->department_name ?? 'class' }}',
        sublimationForm: {
            projectName: projectName,
            description: document.getElementById('sub_description').value,
            garmentType: garmentName,
            garmentId: garment.value,
            fabric: fabricName,
            fabricId: fabric.options[fabric.selectedIndex] ? fabric.options[fabric.selectedIndex].value : '',
            designer: designer,
            dateNeeded: dateNeeded,
            notes: document.getElementById('sub_notes').value,
            sizes: sizes,
            parts: parts,
            specs: specs,
            unitPrice: unitPrice,
            totalQty: totalQty,
            totalPrice: grandTotal,
            rosterMode: isRoster,
            mockupData: mockupData
        },
        quantity: totalQty,
        unitPrice: unitPrice,
        totalPrice: grandTotal
    };
    
    // Apply special price if active
    var sps = document.getElementById('subSpecialPriceSection');
    if (sps.style.display !== 'none') {
        var spReason = document.getElementById('subSpecialPriceReason').value.trim();
        var spVal = parseFloat(document.getElementById('subSpecialPrintTotal').value) || 0;
        if (spVal > 0 && !spReason) { alert('Please provide a reason for the special price.'); return; }
        if (spVal > 0) {
            item.sublimationForm.specialPrice = { price: spVal, reason: spReason };
        }
    }
    
    // Submit
    var btn = document.getElementById('subAddItemBtn');
    btn.disabled = true;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i> Adding...';
    
    fetch('{{ route("sales.prototype.add-product", $sale->id) }}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify(item)
    })
    .then(function(r) { return r.json(); })
    .then(function(data) {
        if (data.success) {
            location.reload();
        } else {
            alert('Error: ' + (data.message || 'Unknown error'));
            btn.disabled = false;
            btn.innerHTML = '<i class="fas fa-check-circle me-2"></i> Add to Order';
        }
    })
    .catch(function(err) {
        alert('Network error: ' + err.message);
        btn.disabled = false;
        btn.innerHTML = '<i class="fas fa-check-circle me-2"></i> Add to Order';
    });
};

// ======= PRINT ORDER SLIP =======
window.sub_printOrderSlip = function() {
    var projectName = document.getElementById('sub_projectName').value.trim() || 'New Product';
    var garmentSelect = document.getElementById('sub_garmentSelect');
    var garmentName = garmentSelect.selectedIndex > 0 ? garmentSelect.options[garmentSelect.selectedIndex].textContent : 'N/A';
    var fabricSelect = document.getElementById('sub_fabricSelect');
    var fabricName = fabricSelect.selectedIndex > 0 ? fabricSelect.options[fabricSelect.selectedIndex].textContent : 'N/A';
    
    // Collect sizes
    var sizesHtml = '';
    document.querySelectorAll('.sub-size-qty').forEach(function(input) {
        var val = parseInt(input.value) || 0;
        if (val > 0) {
            sizesHtml += '<tr><td>' + input.dataset.size + '</td><td>' + val + '</td></tr>';
        }
    });
    
    if (!sizesHtml) {
        document.querySelectorAll('#subRosterBody tr.roster-row').forEach(function(row) {
            var name = row.querySelector('.roster-name');
            var size = row.querySelector('.roster-size');
            if (name && size) {
                sizesHtml += '<tr><td>' + name.value + '</td><td>' + size.value + '</td><td>1</td></tr>';
            }
        });
    }
    
    var orderNumber = '{{ $sale->sales_number }}';
    var customerName = '{{ $sale->customer_name ?? 'N/A' }}';
    var now = new Date();
    var dateStr = now.toLocaleDateString('en-PH', {year:'numeric',month:'long',day:'numeric'});
    
    var printWin = window.open('', '_blank', 'width=800,height=600');
    printWin.document.write('<!DOCTYPE html><html><head><title>Order Slip - ' + projectName + '</title>');
    printWin.document.write('<style>body{font-family:Arial,sans-serif;padding:20px;}table{width:100%;border-collapse:collapse;margin:10px 0;}td,th{border:1px solid #000;padding:5px;text-align:left;}.header{text-align:center;margin-bottom:20px;}.header h1{margin:0;font-size:18pt;}.header h2{margin:0;font-size:14pt;color:#666;}</style></head><body>');
    printWin.document.write('<div class="header"><h1>CLASS APPAREL PH</h1><h2>Order Slip</h2></div>');
    printWin.document.write('<p><strong>Order #:</strong> ' + orderNumber + ' | <strong>Customer:</strong> ' + customerName + ' | <strong>Date:</strong> ' + dateStr + '</p>');
    printWin.document.write('<h3>' + projectName + '</h3>');
    printWin.document.write('<p><strong>Garment:</strong> ' + garmentName + ' | <strong>Fabric:</strong> ' + fabricName + '</p>');
    printWin.document.write('<table><thead><tr><th>Size/Name</th><th>Size</th><th>Qty</th></tr></thead><tbody>' + sizesHtml + '</tbody></table>');
    
    var partsNames = [];
    document.querySelectorAll('#sub_partsContainer .part-checkbox:checked').forEach(function(cb) {
        partsNames.push(cb.value);
    });
    if (partsNames.length) printWin.document.write('<p><strong>Parts:</strong> ' + partsNames.join(', ') + '</p>');
    
    printWin.document.write('<p><strong>Unit Price:</strong> ' + document.getElementById('subPricing_unitPrice').textContent + ' | <strong>Total:</strong> ' + document.getElementById('subPricing_grandTotal').textContent + '</p>');
    printWin.document.write('</body></html>');
    printWin.document.close();
    printWin.print();
};
</script>
